"""The v1 evidence contract, FROZEN. Do not edit this file.

A v1 release emitted before the v2 extension existed must still verify, byte for byte, against
today's code. That is not a courtesy — it is the whole meaning of a content-addressed artifact:
`evidence_inputs_sha256` is a digest of the CONTENT, and if the content is unchanged the digest
must be unchanged. When the v2 columns were first added they went into the shared column set, so
v1 content began hashing under a v2 shape and the digest moved from

    8999c5a38c8df8bb85ef2ca16cf5dd6decdddea81f4b48069cb61b680c47c6f5   (v1, correct)

to a v2-shaped one, and the independent verifier started demanding a `relation` column of
releases written before that column existed. Both were regressions, and both had the same cause:
one mutable declaration serving two contracts.

So the v1 declaration lives here, alone, frozen, and pinned by a test. v2 is expressed as an
ADDITION to it (`evidence_inputs.py`), never as an edit of it. A v1 release carries exactly these
columns — not these columns plus nulls — and hashes exactly as it always did.

Copied verbatim from 04_PKPD/analysis/evidence_inputs.py at commit e410d72.
"""

from __future__ import annotations

# The frozen v1 digest of the v1 fixture set. Pinned so that a change to the v1 contract is
# impossible to make by accident: it fails this pin, in a diff a reviewer will see.
V1_FIXTURE_EVIDENCE_INPUTS_SHA256 = (
    "8999c5a38c8df8bb85ef2ca16cf5dd6decdddea81f4b48069cb61b680c47c6f5"
)

TABLES_V1: tuple[str, ...] = (
    "delivery_evidence", "transporter_evidence", "exposure_evidence", "safety_evidence",
    "nebpi_decisions", "nebpi_criteria",
    "contexts", "drug_forms", "property_evidence", "potency_evidence",
    "potency_context_links", "delivery_assignments", "nebpi_observations",
    "search_manifests", "source_catalog",
)

# The seven method files a v1 release binds into its id. A v1 release verified against today's
# method/ directory must recompute exactly these hashes, so none of these files may be edited
# and none may be added to this map. v2 method content goes in NEW files, listed in
# `METHOD_FILES_V2` -- an edit here would break every release ever emitted.
METHOD_FILES_V1 = {
    "cns_mpo": "cns_mpo_wager2010_v1.json",
    "nebpi": "nebpi_grossman2026_v1.json",
    "calculator_policy": "calculator_policy_v1.json",
    "delivery_rules": "delivery_rules_v1.json",
    "safety_taxonomy": "safety_taxonomy_v1.json",
    "sources": "sources.json",
    "prose": "stage4_prose_v1.json",
}

INPUT_COLUMNS_V1: dict[str, tuple[str, ...]] = {
    "contexts": (
        "context_id", "candidate_id", "active_moiety_id", "route", "formulation", "dose",
        "schedule", "tumor_context", "population", "is_fixture",
    ),
    "property_evidence": (
        "property_record_id", "candidate_id", "active_moiety_id", "property_id",
        "value_source_string", "units", "determination", "calculator_id", "method",
        "software_version", "database_version",
        "source_record_id", "source_url", "access_date", "release_version",
        "raw_response_sha256", "extraction_transform",
    ),
    "potency_evidence": (
        "potency_id", "candidate_id", "active_moiety_id", "metric", "value_source_string",
        "units", "binding_state", "assay", "biological_context", "evidence_type",
        "source_record_id", "source_url", "access_date", "release_version",
        "raw_response_sha256", "extraction_transform",
    ),
    "potency_context_links": (
        "link_id", "potency_id", "tumor_context", "rationale",
        "source_record_id", "source_url", "access_date", "release_version",
        "raw_response_sha256", "extraction_transform",
    ),
    "transporter_evidence": (
        "observation_id", "candidate_id", "active_moiety_id", "transporter",
        "transporter_gene", "interaction", "assay", "species", "biological_system",
        "concentration", "concentration_units", "result_metric", "result_value",
        "result_units", "direction", "evidence_type",
        "source_record_id", "source_url", "access_date", "release_version",
        "raw_response_sha256", "extraction_transform",
    ),
    "exposure_evidence": (
        "measurement_id", "candidate_id", "active_moiety_id", "context_id", "formulation",
        "route", "dose", "schedule", "species_population", "matrix", "enhancement_context",
        "binding_state", "concentration_source_string", "concentration_units",
        "detection_status", "quantitation_limit_kind", "quantitation_limit_source_string",
        "quantitation_limit_units", "timepoint", "kp_reported_source_string",
        "kp_uu_brain_reported_source_string", "evidence_type",
        "source_record_id", "source_url", "access_date", "release_version",
        "raw_response_sha256", "extraction_transform",
    ),
    "delivery_assignments": (
        "assignment_id", "candidate_id", "context_id", "requirement", "basis", "assigned_by",
        "rule_id", "rule_version", "rationale",
        "evidence_source_record_id", "evidence_source_url", "evidence_access_date",
        "evidence_release_version", "evidence_sha256", "evidence_extraction_transform",
    ),
    "nebpi_observations": (
        "observation_id", "candidate_id", "context_id", "criterion_id", "state",
        "assessment_adequate", "adequacy_rationale", "measurement_id", "potency_id",
        "evidence_type",
        "source_record_id", "source_url", "access_date", "release_version",
        "raw_response_sha256", "extraction_transform",
    ),
    "safety_evidence": (
        "evidence_id", "candidate_id", "active_moiety_id", "evidence_state", "finding_type",
        "finding_text", "gbm_scenario", "interaction_type", "label_source", "setid",
        "application_number", "product_identity", "label_version", "effective_date",
        "labeled_section_code", "labeled_section_name", "code_system",
        "labeled_subsection_code", "labeled_subsection_name", "searched_sources",
        "search_id",
        "source_record_id", "source_url", "access_date", "release_version",
        "raw_response_sha256", "extraction_transform",
    ),
    "search_manifests": (
        "search_id", "source", "endpoint", "query_canonical", "search_scope",
        "executed_date", "source_release", "n_results",
        "source_record_id", "source_url", "access_date", "release_version",
        "response_sha256", "extraction_transform",
    ),
}

DERIVED_COLUMNS_V1: dict[str, tuple[str, ...]] = {
    "contexts": (),
    "property_evidence": (
        "value_canonical_decimal", "value_in_base_units", "base_units", "unit_conversion",
        "method_conformance", "component_score_t0", "accepted", "rejection_reason_code",
    ),
    "potency_evidence": ("value_canonical_decimal",),
    "potency_context_links": (),
    "transporter_evidence": (),
    "exposure_evidence": (
        "concentration_canonical_decimal", "quantitation_limit_canonical_decimal",
        "margin_status", "margin", "margin_canonical_decimal", "margin_reason_code",
        "harmonized_units", "exposure_harmonized", "potency_harmonized",
        "potency_id", "potency_context_link_id", "margin_transform", "caveats",
    ),
    "delivery_assignments": (),
    "nebpi_observations": (),
    "safety_evidence": ("renders_as_safe", "evidence_state_display"),
    "search_manifests": (),
}
