"""THE SIGN RULE — the one front door. See :mod:`druglink.modality_contract` for the rule
itself and :mod:`druglink.modality_gates_v2` for the refusals re-asserted on emitted rows.

Split at the 500-line gate; consumers bind THIS module and nothing changes for them.
"""
from __future__ import annotations

from .modality_contract import *          # noqa: F401,F403  (the tokens)
from .modality_rule import *              # noqa: F401,F403  (the rule)
from .modality_rule import (              # noqa: F401  (explicit, for the linters)
    ACTION_ACTIVATE,
    ACTION_INHIBIT,
    ACTION_PHENOCOPY_EFFECTS,
    ARM_VALUE_IS_PRE_ORIENTED_BY_STAGE2,
    EVIDENCE_RELATIONS,
    FIELD_ARM_VALUE,
    FIELD_EVALUABLE,
    FIELD_MODALITY,
    FIELD_MODULATION,
    FIELD_NAMESPACE,
    FIELD_PHENOCOPY_CLASS,
    GATE_EVALUABILITY_NOT_DECLARED,
    GATE_HIT_COUNT_COUNTED_ROWS_NOT_RANKS,
    GATE_INFERRED_ORIGIN_PRODUCED_A_DRUG_EDGE,
    GATE_MODALITY_NOT_DECLARED,
    GATE_NAMESPACE_MISTYPED,
    GATE_NAMESPACE_NOT_DECLARED,
    GATE_NAMESPACE_VOCABULARY_DIVERGENCE,
    GATE_PHENOCOPY_CLASS_NOT_DECLARED,
    GATE_SERIALIZED_MODULATION_DISAGREES_WITH_THE_SIGN,
    GATE_SIGN_READ_FROM_AN_INFERRED_ROW,
    GATE_UNKNOWN_MODALITY,
    GATE_UNKNOWN_NAMESPACE,
    GATE_UNKNOWN_SERIALIZED_MODULATION,
    INVERSE_ACTION,
    MATCH_ARM_NOT_EVALUABLE,
    MATCH_COMPATIBLE,
    MATCH_EFFECT_UNKNOWN,
    MATCH_NO_DIRECTIONAL_RESPONSE,
    MATCH_OPPOSES_OBSERVED_BENEFIT,
    MATCH_PHENOCOPIES_UNDESIRED,
    MATCH_STATUSES,
    MATCH_UNTESTED_INVERSE,
    MOD_DECREASE,
    MOD_INCREASE,
    MOD_NO_DIRECTION,
    MOD_NOT_EVALUATED,
    MODALITY_CRISPRA,
    MODALITY_CRISPRI,
    MODALITY_PERFORMED_ACTION,
    MODALITY_V2_POLICY_VERSION,
    MODULATION_FOR,
    PHARMACOLOGIC_REVERSIBILITY_ASSUMED,
    PHENOCOPY_CAVEAT,
    PHENOCOPY_RELATION,
    PHENOCOPY_RELATIONS,
    RELATION_EFFECT_NOT_ENUMERATED,
    RELATION_UNTESTED_INVERSE,
    SIGN_EPS,
    SIGN_EPS_BASIS,
    SIGN_NO_DIRECTIONAL_RESPONSE,
    SIGN_NOT_EVALUABLE,
    SIGN_OPPOSES_DESIRED_CHANGE,
    SIGN_STATES,
    SIGN_SUPPORTS_DESIRED_CHANGE,
    TARGET_MODULATIONS,
    W3_NAMESPACES,
    W3_REQUIRED_ROW_FIELDS,
    ModalityError,
    check_namespace_against_store,
    check_serialized_modulation,
    check_store_namespace_vocabulary,
    classify,
    declared_modality,
    desired_target_modulation,
    evaluable_of,
    evidence_relation,
    is_inverse_mechanism,
    namespace_of,
    observed_compatible_action,
    observed_sign_state,
    phenocopies,
    phenocopy_class_of,
    phenocopying_actions,
    untested_inverse_action,
    vocabularies,
)
from .modality_gates_v2 import (          # noqa: F401  (the refusals, on emitted rows)
    GATE_CLAIMS_EQUIVALENCE,
    GATE_MODULATION_DERIVED_FROM_MODALITY_ALONE,
    GATE_NO_EVIDENCE_RELATION,
    GATE_NON_PHENOCOPY_IN_SUPPORTED_EVIDENCE,
    GATE_SUPPORTED_ON_A_NON_SUPPORTING_SIGN,
    check_edge_relation,
    check_edges,
    check_no_agonist_supported,
    check_sign_rule,
)
