"""Disk-backed admission of the REAL Stage-2 aggregate release. THE production gate.

This module previously parsed a Stage-2 schema that **does not exist**. It read
``inventory[]``, ``stage1_release.raw_sha256``, ``artifact_class`` and an ``admits{}``
block, and it required the substring ``"independent"`` in the verifier id. Stage 2 emits
none of those. Its tests passed only because one author wrote both the loader and the
fixture it parsed — a self-consistent fiction that could not ingest one byte of the real
thing.

The contract below is TRANSCRIBED FROM STAGE-2's ACTUAL GENERATED BYTES — the manifest and
the admission report its real CLIs emitted and its own separate verifier admitted — not from
a shape Stage 3 invented for itself. The test fixture parses those same bytes verbatim
(``tests/stage2_release_fixture.py``), so the loader cannot drift from the producer without a
test failing. That is the whole repair: the old fixture COULD drift, and did, silently.

THE NATIVE CONTRACT
-------------------
manifest  ``spot.stage02_run_manifest.v3_topology_only`` — top-level ``bundles[]`` (each an
          all-arm bundle DIRECTORY: an ``out_dir`` NAME + a ``files{}`` map + ``arm_keys``),
          the bound ``stage1_v3_release``, and a ``manifest_sha256`` that is the producer's
          SEMANTIC self-hash: the canonical content hash of the document EXCLUDING
          ``created_at``, ``manifest_sha256`` and ``path``. We RE-DERIVE it, never read it.
report    ``spot.stage02_run_manifest_verification.v1`` — a SEPARATE artifact from
          ``spot.stage02.run_manifest.verifier.v1``. Its id does not contain the word
          "independent", and never did: independence is asserted by the STRUCTURED FIELD
          ``generator_is_not_verifier``. A name is not a binding, so THAT is what we bind.

WHAT WE DELIBERATELY DO **NOT** BIND. Stage-2's *source* defines a ``stage3_inputs`` handoff
receipt (``spot.stage02.stage3_handoff.v1``), and it would be the natural thing to consume —
but it is **ABSENT from the actually-generated report**. Binding a field the real producer
does not emit is the very error this module exists to fix, so Stage 3 binds the FOUR PATHS
EXPLICITLY (manifest, report, bundles root, Stage-1 release) and reads nothing that the bytes
on disk do not contain. If Stage 2 ever ships the receipt, that is the day to bind it.

WHAT ADMITS A RELEASE. Stage 2 declares no ``artifact_class``, so the old fixture-firewall
keyed on a field that does not exist. The real gate is Stage-2's own admission, which a
fixture cannot forge out of Stage-2's real verifier:

    verdict == "admit"  AND  admission.status == "admitted"
    AND generator_is_not_verifier is True   AND  n_failed == 0
    AND topology_complete is True           AND  release_admissible is True
    AND the report's manifest_sha256 == the semantic self-hash WE recompute from the
        manifest bytes on disk

Stage-3's OWN ``--artifact-class`` stays (Stage-3's declaration about Stage-3's output,
never Stage-2's) and :func:`require_analysis` still enforces it.

Every refusal is a NAMED gate. Fail closed. A missing field is a refusal, never a default.
"""
from __future__ import annotations

import os
from typing import Any

from . import artifact_class as ac
from . import stage2_contract as C
from .stage2_bridge import (  # noqa: F401  (the BRIDGE consumer; one front door)
    BRIDGE_SCHEMA,
    CTX_FORBIDDEN,
    GATE_BRIDGE_BINDS_NOTHING,
    GATE_BRIDGE_IS_EMPTY,
    GATE_BRIDGE_NOT_NATIVE,
    GATE_BRIDGE_NOT_ON_DISK,
    GATE_BRIDGE_OVER_ANOTHER_AGGREGATE,
    GATE_BRIDGE_SELF_HASH,
    GATE_MODULATION_DISAGREES_WITH_SIGN,
    GATE_PATHWAY_CONTEXT_IS_TARGET_EVIDENCE,
    GATE_PATHWAY_SOURCED_A_TYPED_ROW,
    GATE_RECEIPT_ABSENT,
    GATE_RECEIPT_BINDS_OTHER_BYTES,
    GATE_RECEIPT_NOT_NATIVE,
    GATE_RECEIPT_SELF_HASH,
    GATE_BRIDGE_REPORT_NOT_NATIVE,
    GATE_REPORT_JUDGED_OTHER_BYTES,
    GATE_REPORT_NOT_ADMIT,
    GATE_ROW_CHANGES_A_NATIVE_FACT,
    GATE_ROW_DROPPED,
    GATE_ROW_IDENTITY_NOT_TYPED,
    GATE_ROW_MODALITY_NOT_DECLARED,
    GATE_ROW_ORPHAN,
    RECEIPT_SCHEMA,
    SIGN_EPS,
    AdmittedBridge,
    Stage2BridgeError,
    admit_bridge,
    bridge_provenance_rows,
    native_index,
    rederive_modulation,
    typed_aggregate,
)
from .stage2_contract import (  # noqa: F401  (the public API; downstream imports it here)
    ADMIT,
    ADMITTED,
    AGGREGATE_VERIFIER_ID,
    ARM_BUNDLE_FILE,
    CONDITIONS,
    CONTEXT_FIELDS,
    DESIRED_CHANGES,
    GATE_ADMISSION_NOT_GRANTED,
    GATE_ARM_INDEX_DISAGREES,
    GATE_ARTIFACT_NOT_ON_DISK,
    GATE_BUNDLE_BYTES_MOVED,
    GATE_DUPLICATE_BUNDLE,
    GATE_FIXTURE_FIREWALL,
    GATE_GATES_FAILED,
    GATE_GENERATOR_IS_VERIFIER,
    GATE_INCOMPLETE_TOPOLOGY,
    GATE_MANIFEST_NOT_NATIVE,
    GATE_MANIFEST_SELF_HASH,
    GATE_MANIFEST_UNREADABLE,
    GATE_MISSING_BUNDLE,
    GATE_NOT_RELEASE_ADMISSIBLE,
    GATE_PATH_TRAVERSAL,
    GATE_RELEASE_IS_NOT_THE_PINNED_ONE,
    GATE_REPORT_BINDS_ANOTHER_MANIFEST,
    GATE_REPORT_NOT_NATIVE,
    GATE_SELF_ADMISSION,
    GATE_STAGE1_RELEASE_UNBOUND,
    GATE_TOPOLOGY_NOT_COMPLETE,
    GATE_UNKNOWN_LANE,
    GATE_VERDICT_NOT_ADMIT,
    GATE_VERIFIER_NOT_PINNED,
    LANE_DIRECT,
    LANE_PATHWAY,
    LANE_TEMPORAL,
    LANES,
    MANIFEST_SCHEMA,
    MEASURED_LANES,
    N_ARM_SLOTS,
    N_BUNDLES,
    N_PROGRAMS,
    PATHWAY_SOURCES,
    REPORT_SCHEMA,
    SELF_HASH_EXCLUDED,
    SELF_HASH_FIELD,
    AdmittedAggregate,
    AdmittedBundle,
    AggregateAdmissionRefused,
    AggregateTopologyRefused,
    LoadedArm,
    Stage2AggregateError,
    expected_bundle_keys,
    manifest_self_hash,
    ordered_condition_pairs,
    stage2_content_sha256,
)

_refuse = C._refuse


# --- 1. Identity, and STAGE-2's OWN ADMISSION. ------------------------------- #
def _check_manifest_identity(manifest: dict[str, Any]) -> str:
    """It recomputes its own semantic identity, or nothing it says about anything stands."""
    declared = manifest.get(SELF_HASH_FIELD)
    recomputed = manifest_self_hash(manifest)
    if declared != recomputed:
        _refuse(GATE_MANIFEST_SELF_HASH,
                f"the manifest declares {SELF_HASH_FIELD}={str(declared)[:16]}… but its own "
                f"semantic content hashes to {recomputed[:16]}…. A manifest that cannot prove "
                "its own identity is not a root of trust; it is a document asserting a "
                "number.")
    return recomputed


def _check_report(report: dict[str, Any], *, self_hash: str) -> tuple[str, str]:
    """Stage-2's OWN admission. Every clause is a separate, named gate."""
    verifier_id = str(report.get("verifier_id") or "")
    if verifier_id != AGGREGATE_VERIFIER_ID:
        _refuse(GATE_VERIFIER_NOT_PINNED,
                f"the report is signed {verifier_id!r}; the pinned aggregate verifier is "
                f"{AGGREGATE_VERIFIER_ID!r}.")
    # INDEPENDENCE IS A STRUCTURED FIELD, NOT A NAME. The retired gate required the substring
    # "independent" in the verifier id — which the real verifier's id does not contain, so it
    # would have REFUSED the genuine report while ADMITTING any forgery that merely named
    # itself "…independent…". A substring proves nothing; this field is the assertion.
    if report.get("generator_is_not_verifier") is not True:
        _refuse(GATE_GENERATOR_IS_VERIFIER,
                "the report does not assert generator_is_not_verifier=true. A producer "
                "agreeing with itself is the one thing an independent verifier exists to rule "
                "out, and a missing assertion is a refusal, never a default.")
    verdict = report.get("verdict")
    if verdict != ADMIT:
        _refuse(GATE_VERDICT_NOT_ADMIT,
                f"the aggregate verifier's verdict is {verdict!r}, not {ADMIT!r}")
    if report.get("n_failed") != 0:
        _refuse(GATE_GATES_FAILED,
                f"the aggregate verifier recorded n_failed={report.get('n_failed')!r} "
                f"({report.get('failed_gates')}); a release with a failed gate is not "
                "admitted, whatever its verdict string says.")
    if report.get("topology_complete") is not True:
        _refuse(GATE_TOPOLOGY_NOT_COMPLETE,
                f"the verifier found topology_complete={report.get('topology_complete')!r}: "
                "a partial run is never release-admissible.")
    if report.get("release_admissible") is not True:
        _refuse(GATE_NOT_RELEASE_ADMISSIBLE,
                f"the verifier found release_admissible="
                f"{report.get('release_admissible')!r}.")
    status = (report.get("admission") or {}).get("status")
    if status != ADMITTED:
        _refuse(GATE_ADMISSION_NOT_GRANTED,
                f"admission.status is {status!r}, not {ADMITTED!r}. Admission is granted by "
                "the independent aggregate report, or not at all.")
    # THE REPORT MUST ADMIT *THESE* BYTES. Both its claim and its own recomputation must equal
    # the self-hash WE derived from the manifest on disk — so a report about some other
    # manifest, and a manifest edited after it was judged, are the same refusal.
    claimed = report.get(SELF_HASH_FIELD)
    recomputed = report.get("manifest_sha256_recomputed")
    if claimed != self_hash or recomputed != self_hash:
        _refuse(GATE_REPORT_BINDS_ANOTHER_MANIFEST,
                f"the report admits manifest {str(claimed)[:16]}… (it recomputed "
                f"{str(recomputed)[:16]}…), but the manifest on disk semantically hashes to "
                f"{self_hash[:16]}…. An ADMIT that names other bytes is an opinion about some "
                "other artifact.")
    return verifier_id, str(verdict)


def _check_stage1_release(manifest: dict[str, Any], stage1_release_path: str) -> str:
    """The release the aggregate was computed against, bound to the bytes it names."""
    bound = manifest.get("stage1_v3_release") or {}
    pinned = bound.get("release_canonical_sha256")
    if not pinned:
        _refuse(GATE_STAGE1_RELEASE_UNBOUND,
                "the manifest pins no stage1_v3_release.release_canonical_sha256: an "
                "aggregate that cannot name the release it stands on cannot be replayed "
                "against it.")
    release, raw = C.load_json(stage1_release_path, "pinned Stage-1 v3 release")
    on_disk = stage2_content_sha256(release)
    if on_disk != pinned:
        _refuse(GATE_STAGE1_RELEASE_UNBOUND,
                f"the Stage-1 release on disk canonically hashes to {on_disk[:16]}… but the "
                f"manifest pins {str(pinned)[:16]}…: a DIFFERENT release than the aggregate "
                "was computed against.")
    declared_raw = bound.get("release_raw_sha256")
    if declared_raw and declared_raw != raw:
        _refuse(GATE_STAGE1_RELEASE_UNBOUND,
                f"the Stage-1 release BYTES on disk hash to {raw[:16]}… but the manifest bound "
                f"{str(declared_raw)[:16]}…: the file was re-serialised after the run.")
    return on_disk



# --- The gate. -------------------------------------------------------------- #
def admit_aggregate(*, manifest_path: str, report_path: str, bundles_root: str,
                    stage1_release_path: str,
                    artifact_class: str = ac.FIXTURE) -> AdmittedAggregate:
    """Admit the REAL Stage-2 aggregate FROM DISK, or refuse by name.

    ``artifact_class`` is STAGE-3's own declaration about what Stage 3 is doing with this
    release (its ``--artifact-class`` flag). Stage 2 declares none, and never did: the gate on
    the RELEASE is Stage-2's own admission, checked in :func:`_check_report`.
    """
    klass = ac.require(str(artifact_class or ""))
    if os.path.realpath(manifest_path) == os.path.realpath(report_path):
        _refuse(GATE_SELF_ADMISSION,
                "the report and the manifest are the SAME file. A producer does not admit "
                "itself: the report is a separate artifact from a separate verifier.")

    manifest, manifest_raw = C.load_json(manifest_path, "Stage-2 aggregate run manifest")
    C.require_schema(manifest, MANIFEST_SCHEMA, GATE_MANIFEST_NOT_NATIVE,
                    "Stage-2 aggregate run manifest")
    report, _ = C.load_json(report_path, "Stage-2 aggregate verification report")
    C.require_schema(report, REPORT_SCHEMA, GATE_REPORT_NOT_NATIVE,
                    "Stage-2 aggregate verification report")

    self_hash = _check_manifest_identity(manifest)
    verifier_id, verdict = _check_report(report, self_hash=self_hash)
    stage1_sha = _check_stage1_release(manifest, stage1_release_path)
    programs, conditions, sources = C.release_topology(manifest)

    manifest_canonical = stage2_content_sha256(manifest)
    provenance = {"manifest_raw_sha256": manifest_raw,
                  "manifest_canonical_sha256": manifest_canonical,
                  "manifest_self_hash": self_hash, "aggregate_verifier_id": verifier_id,
                  "aggregate_verdict": verdict, "stage1_release_sha256": stage1_sha}

    bound = C.check_bundles(manifest, bundles_root, conditions=conditions, sources=sources)
    arms: list[LoadedArm] = []
    for bundle, full, entry in bound:
        arms.extend(C.load_bundle_arms(bundle, full, entry, provenance=provenance))
    bundles = [b for b, _f, _e in bound]
    program_ids = C.check_arm_topology(arms, bundles, programs)

    return AdmittedAggregate(
        artifact_class=klass, manifest_raw_sha256=manifest_raw,
        manifest_canonical_sha256=manifest_canonical, manifest_self_hash=self_hash,
        verifier_id=verifier_id, verdict=verdict, stage1_release_sha256=stage1_sha,
        bundles=tuple(bundles), arms=tuple(arms), program_ids=program_ids,
        counts={"n_bundles": len(bundles), "n_arm_slots": len(arms),
                "n_programs": len(program_ids),
                "bundles_per_lane": {ln: sum(b.lane == ln for b in bundles) for ln in LANES},
                "arms_per_lane": {ln: sum(a.lane == ln for a in arms) for ln in LANES},
                "topology_is_derived_not_declared": True,
                "combined_objective_permitted": False, "pair_roles_assigned": False})


def require_analysis(admitted: AdmittedAggregate) -> AdmittedAggregate:
    """Stage-3's fixture firewall, on STAGE-3's own class: a sealed test run never becomes a
    real analysis. (This is not the Stage-2 gate — that is the admission above.)"""
    if admitted.artifact_class != ac.ANALYSIS:
        _refuse(GATE_FIXTURE_FIREWALL,
                f"the run declares artifact_class={admitted.artifact_class!r}; only an "
                "'analysis' run may enter the analysis path — a synthetic number on its way to "
                "Stage 4 is a fabricated candidate.")
    return admitted
