"""The NATIVE Stage-2 contract, and the BYTES that prove it.

The vocabulary of Stage-2's real aggregate release — its schemas, its named refusal gates,
its content-hash rule, its slot algebra — plus the code that re-reads the 15 all-arm bundle
DIRECTORIES from disk and proves every byte the manifest bound.

This is the lower layer. It answers "what IS this artifact, and are these its bytes?".
Whether Stage 2 ADMITTED it is a separate question, asked by :mod:`druglink.stage2_aggregate`,
which imports from here. Splitting them keeps each module to one purpose (and under the
500-line rule); the public API stays on ``stage2_aggregate``, which re-exports these names.

The contract was replayed from Stage-2's ACTUAL generated bytes — not from its source, and
certainly not from a shape Stage 3 invented for itself. See ``stage2_aggregate`` for the full
account of what that invented shape was and why it could never ingest a real release.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass, field
from typing import Any, Optional

from .hashing import file_sha256, without

MANIFEST_SCHEMA = "spot.stage02_run_manifest.v3_topology_only"
REPORT_SCHEMA = "spot.stage02_run_manifest_verification.v1"
AGGREGATE_VERIFIER_ID = "spot.stage02.run_manifest.verifier.v1"

ADMIT = "admit"
ADMITTED = "admitted"

SELF_HASH_FIELD = "manifest_sha256"
SELF_HASH_EXCLUDED = ("created_at", "manifest_sha256", "path")

# The release this Stage-3 is pinned to. The slot algebra is DERIVED from the manifest's own
# bound release (below); these are the expectation a DIFFERENT release trips over.
CONDITIONS = ("Rest", "Stim8hr", "Stim48hr")
PATHWAY_SOURCES = ("GO-BP", "Reactome")
DESIRED_CHANGES = ("increase", "decrease")
N_PROGRAMS = 10

LANE_DIRECT = "direct"
LANE_TEMPORAL = "temporal"
LANE_PATHWAY = "pathway"
LANES = (LANE_DIRECT, LANE_TEMPORAL, LANE_PATHWAY)
MEASURED_LANES = frozenset({LANE_DIRECT, LANE_TEMPORAL})
CONTEXT_FIELDS = ("condition", "from_condition", "to_condition", "pathway_source")

# Stage 2 names the pathway axis ``gene_set_source`` in a bundle context; Stage 3 has always
# called it ``pathway_source``. The rename happens HERE, once, and is recorded.
NATIVE_PATHWAY_SOURCE_KEY = "gene_set_source"
ARM_BUNDLE_FILE = "arm_bundle.json"

# Named gates. Every refusal names one, so it can be grepped, tested and cited.
GATE_ARTIFACT_NOT_ON_DISK: str = "aggregate_artifact_is_not_on_disk"
GATE_MANIFEST_UNREADABLE: str = "aggregate_artifact_is_not_readable_json"
GATE_MANIFEST_NOT_NATIVE: str = "manifest_is_not_the_native_stage2_run_manifest_schema"
GATE_MANIFEST_SELF_HASH: str = "manifest_does_not_recompute_its_own_semantic_self_hash"
GATE_SELF_ADMISSION: str = "the_report_and_the_manifest_are_the_same_artifact"
GATE_REPORT_NOT_NATIVE: str = "report_is_not_the_native_stage2_verification_schema"
GATE_VERIFIER_NOT_PINNED: str = "report_was_not_written_by_the_pinned_aggregate_verifier"
GATE_GENERATOR_IS_VERIFIER: str = "report_does_not_assert_generator_is_not_verifier"
GATE_VERDICT_NOT_ADMIT: str = "the_aggregate_verifier_did_not_say_admit"
GATE_GATES_FAILED: str = "the_aggregate_verifier_recorded_failed_gates"
GATE_TOPOLOGY_NOT_COMPLETE: str = "the_verifier_did_not_find_the_topology_complete"
GATE_NOT_RELEASE_ADMISSIBLE: str = "the_verifier_did_not_find_the_release_admissible"
GATE_ADMISSION_NOT_GRANTED: str = "the_admission_status_is_not_admitted"
GATE_REPORT_BINDS_ANOTHER_MANIFEST: str = "the_report_admits_a_different_manifest"
GATE_STAGE1_RELEASE_UNBOUND: str = "stage1_release_on_disk_is_not_the_pinned_release"
GATE_RELEASE_IS_NOT_THE_PINNED_ONE: str = "the_manifest_binds_a_different_stage1_release"
GATE_PATH_TRAVERSAL: str = "bundle_path_escapes_the_bundles_root"
GATE_UNKNOWN_LANE: str = "the_manifest_names_a_lane_or_context_the_release_does_not_have"
GATE_DUPLICATE_BUNDLE: str = "the_manifest_carries_a_duplicate_bundle"
GATE_MISSING_BUNDLE: str = "the_manifest_is_missing_a_bundle_the_release_must_have"
GATE_INCOMPLETE_TOPOLOGY: str = "the_release_does_not_resolve_its_full_arm_topology"
GATE_BUNDLE_BYTES_MOVED: str = "bundle_bytes_on_disk_are_not_the_bytes_the_manifest_bound"
GATE_ARM_INDEX_DISAGREES: str = "the_manifests_arm_index_disagrees_with_the_bundles_bytes"
GATE_FIXTURE_FIREWALL: str = "a_fixture_aggregate_cannot_enter_the_analysis_path"


class Stage2AggregateError(ValueError):
    """The Stage-2 aggregate on disk is not admissible."""


class AggregateAdmissionRefused(Stage2AggregateError):
    """The admission chain (receipt -> report -> manifest -> bytes) does not close."""


class AggregateTopologyRefused(Stage2AggregateError):
    """The release is not the complete 15-bundle / 300-arm topology."""


def _refuse(gate: str, message: str, *, topology: bool = False) -> None:
    """Fail closed, by name. Never a silent pass, never a fixture fallback."""
    exc = AggregateTopologyRefused if topology else AggregateAdmissionRefused
    raise exc(f"[{gate}] {message}")


def stage2_content_sha256(obj: Any) -> str:
    """Stage-2's content hash: keys SORTED, array order PRESERVED, no NaN.

    Reimplemented from Stage-2's written spec rather than imported: this is the rule the
    number under test was computed under, and a verifier that borrows the producer's hasher
    cannot disagree with it. Stage-3's own ``hashing.content_hash`` REFUSES floats — a
    Stage-3 rule for Stage-3 content. Hashing Stage-2's document under it would fail for the
    WRONG reason, and a wrong-reason failure teaches the next reader to add an exception.
    """
    return hashlib.sha256(
        json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=True,
                   allow_nan=False).encode("utf-8")).hexdigest()


def manifest_self_hash(manifest: dict[str, Any]) -> str:
    """The producer's SEMANTIC self-hash, re-derived from the manifest's own content."""
    return stage2_content_sha256(without(manifest, SELF_HASH_EXCLUDED))


# --- What a loaded arm retains. No role, no pole, no score. ------------------ #
@dataclass(frozen=True)
class AdmittedBundle:
    bundle_key: str                    # Stage-3's slot label, derived from the native context
    bundle_id: str                     # Stage-2's OWN bundle identity
    lane: str
    path: str                          # the out_dir NAME, resolved inside bundles_root
    # A bundle is a DIRECTORY: it has no single "raw" hash. These are the two real identities
    # Stage 2 publishes, both re-derived from disk here.
    raw_sha256: str                    # sha256 of the bundle's own arm_bundle.json BYTES
    canonical_sha256: str              # Stage-2's artifact_sha256: content hash of files{}
    files: dict[str, str] = field(default_factory=dict)     # rel path -> sha256, all verified
    condition: Optional[str] = None
    from_condition: Optional[str] = None
    to_condition: Optional[str] = None
    pathway_source: Optional[str] = None       # Stage-2's context ``gene_set_source``


@dataclass(frozen=True)
class LoadedArm:
    arm_key: str
    lane: str
    program_id: str
    desired_change: str
    bundle: AdmittedBundle             # the arm's context: one source of truth
    ranking: dict[str, Any]            # {path, raw_sha256, canonical_sha256}, verified
    provenance: dict[str, Any]
    # The bound ranking's rows, VERBATIM. Stage-2's reusable arm rankings carry exactly
    # {target_id, arm_value, evaluable, rank} — no namespace, no symbol, no modulation.
    # Nothing is renamed and nothing is defaulted in: a field Stage 2 does not emit is a
    # field Stage 3 does not have.
    records: tuple[dict[str, Any], ...]


@dataclass(frozen=True)
class AdmittedAggregate:
    artifact_class: str                # STAGE-3's declaration. Stage 2 declares none.
    manifest_raw_sha256: str
    manifest_canonical_sha256: str
    manifest_self_hash: str            # the producer's semantic self-hash, re-derived
    verifier_id: str
    verdict: str
    stage1_release_sha256: str
    bundles: tuple[AdmittedBundle, ...]
    arms: tuple[LoadedArm, ...]
    program_ids: tuple[str, ...]
    counts: dict[str, Any] = field(default_factory=dict)



# --- 1. Identity. ------------------------------------------------------------ #
def load_json(path: str, what: str) -> tuple[Any, str]:
    """Return (parsed, raw_sha256). Raw is the sha256 of the BYTES ON DISK."""
    if not os.path.isfile(path):
        _refuse(GATE_ARTIFACT_NOT_ON_DISK,
                f"the {what} is not on disk at {path!r}. There is no fixture fallback: a run "
                "without its admitted Stage-2 aggregate does not quietly become one with a "
                "synthetic aggregate.")
    try:
        with open(path, "r", encoding="utf-8") as fh:
            doc = json.load(fh)
    except json.JSONDecodeError as exc:
        _refuse(GATE_MANIFEST_UNREADABLE,
                f"the {what} at {path!r} is not readable JSON: {exc}. Arbitrary bytes under "
                "an expected filename are not an artifact.")
    return doc, file_sha256(path)


def require_schema(doc: Any, want: str, gate: str, what: str) -> dict[str, Any]:
    """The document IS the native artifact, or it is some other document."""
    if not isinstance(doc, dict):
        _refuse(gate, f"the {what} is not a JSON object")
    got = doc.get("schema_version")
    if got != want:
        _refuse(gate,
                f"the {what} declares schema_version={got!r}; the native Stage-2 contract is "
                f"{want!r}. A document Stage 2 never emitted is not evidence Stage 2 "
                "produced — and a shape Stage 3 invented for itself is not a contract.")
    return doc



# --- 2. Topology, DERIVED from the manifest's own bound release. -------------- #
def ordered_condition_pairs(conditions=CONDITIONS) -> tuple[tuple[str, str], ...]:
    """Every ORDERED pair. Rest→Stim48hr is not Stim48hr→Rest: the DiD changes sign."""
    return tuple((a, b) for a in conditions for b in conditions if a != b)


def expected_bundle_keys(conditions=CONDITIONS, sources=PATHWAY_SOURCES) -> dict[str, str]:
    """The bundle slots the release must fill -> their lane. Derived, never declared."""
    keys = {f"{LANE_DIRECT}|{c}": LANE_DIRECT for c in conditions}
    keys.update({f"{LANE_TEMPORAL}|{a}|{b}": LANE_TEMPORAL
                 for a, b in ordered_condition_pairs(conditions)})
    keys.update({f"{LANE_PATHWAY}|{c}|{s}": LANE_PATHWAY
                 for c in conditions for s in sources})
    return keys


N_BUNDLES = len(expected_bundle_keys())                          # 15
N_ARM_SLOTS = N_BUNDLES * N_PROGRAMS * len(DESIRED_CHANGES)      # 300


def release_topology(manifest: dict[str, Any]) -> tuple[list[str], list[str], list[str]]:
    """(programs, conditions, sources) from the manifest's BOUND release. Never a constant."""
    bound = manifest.get("stage1_v3_release") or {}
    programs = sorted(bound.get("programs") or [])
    conditions = list(bound.get("conditions") or [])
    sources = list(bound.get("gene_set_sources") or [])
    if not programs or not conditions or not sources:
        _refuse(GATE_INCOMPLETE_TOPOLOGY,
                "the manifest's bound Stage-1 release names no programs, conditions or "
                "gene-set sources; the topology is DERIVED from the release, and a release "
                "that declares none cannot say what a complete run is.", topology=True)
    if (sorted(conditions) != sorted(CONDITIONS)
            or sorted(sources) != sorted(PATHWAY_SOURCES)
            or len(programs) != N_PROGRAMS):
        _refuse(GATE_RELEASE_IS_NOT_THE_PINNED_ONE,
                f"the manifest binds a release of {len(programs)} programs x {conditions} x "
                f"{sources}; Stage 3 is pinned to {N_PROGRAMS} x {list(CONDITIONS)} x "
                f"{list(PATHWAY_SOURCES)}. A different release is a different aggregate, and "
                "its arms are not these arms.")
    return programs, conditions, sources


def bundle_key_of(lane: str, ctx: dict[str, Any]) -> str:
    """Stage-3's slot label, derived from the bundle's OWN native context."""
    if lane == LANE_DIRECT:
        return f"{LANE_DIRECT}|{ctx.get('condition')}"
    if lane == LANE_TEMPORAL:
        return f"{LANE_TEMPORAL}|{ctx.get('from_condition')}|{ctx.get('to_condition')}"
    return f"{LANE_PATHWAY}|{ctx.get('condition')}|{ctx.get(NATIVE_PATHWAY_SOURCE_KEY)}"


def _resolve_dir(name: Any, root: str, what: str) -> str:
    """Resolve an out_dir NAME to exactly one directory INSIDE root, or refuse.

    Stage 2 stores a bare basename and finds it by walking. We require a bare name (so an
    absolute path and ``..`` never resolve), and we refuse AMBIGUITY: two directories of the
    same name under one root are two bundles claiming one identity, and taking the first
    match would let the loser's bytes go unread.
    """
    if not isinstance(name, str) or not name:
        _refuse(GATE_PATH_TRAVERSAL, f"{what} names no out_dir")
    if os.path.isabs(name) or "/" in name or "\\" in name or name in (".", ".."):
        _refuse(GATE_PATH_TRAVERSAL,
                f"{what} out_dir {name!r} is not a bare directory name: an absolute or "
                "traversing path reads bytes from outside the admitted bundles root.")
    real_root = os.path.realpath(root)
    hits = [os.path.join(base, d)
            for base, dirs, _f in os.walk(real_root) for d in dirs if d == name]
    if not hits:
        _refuse(GATE_ARTIFACT_NOT_ON_DISK,
                f"{what} names bundle directory {name!r}, which is not under the bundles root")
    if len(hits) > 1:
        _refuse(GATE_DUPLICATE_BUNDLE,
                f"{what} out_dir {name!r} resolves to {len(hits)} directories; two bundles "
                "claiming one identity means one of them is never read.")
    full = os.path.realpath(hits[0])
    if os.path.commonpath([real_root, full]) != real_root:
        _refuse(GATE_PATH_TRAVERSAL,
                f"{what} resolves OUTSIDE the bundles root ({full!r}); a symlink counts — "
                "realpath is what gets opened.")
    return full


def _safe_file(rel: Any, base: str, what: str) -> str:
    """A bundle-relative file path that cannot escape its bundle."""
    if not isinstance(rel, str) or not rel:
        _refuse(GATE_PATH_TRAVERSAL, f"{what} names no path")
    if os.path.isabs(rel) or ".." in rel.replace("\\", "/").split("/"):
        _refuse(GATE_PATH_TRAVERSAL,
                f"{what} path {rel!r} is absolute or traverses upwards, out of the bundle.")
    real_base = os.path.realpath(base)
    full = os.path.realpath(os.path.join(real_base, rel))
    if os.path.commonpath([real_base, full]) != real_base:
        _refuse(GATE_PATH_TRAVERSAL,
                f"{what} path {rel!r} resolves outside its bundle ({full!r}).")
    return full


def check_bundles(manifest: dict[str, Any], bundles_root: str, *, conditions: list[str],
                   sources: list[str]) -> list[tuple[AdmittedBundle, str, dict[str, Any]]]:
    """The bundles: known, distinct, complete, inside the root, and byte-true on disk."""
    entries = manifest.get("bundles")
    if not isinstance(entries, list) or not entries:
        _refuse(GATE_INCOMPLETE_TOPOLOGY,
                f"the manifest ships no `bundles` array; the release is exactly {N_BUNDLES} "
                "bundles, and a partial release is never admissible. (An `inventory` array is "
                "not this contract: Stage 2 has never emitted one.)", topology=True)

    expected = expected_bundle_keys(conditions, sources)
    seen: dict[str, AdmittedBundle] = {}
    out: list[tuple[AdmittedBundle, str, dict[str, Any]]] = []
    for entry in entries:
        lane, ctx = entry.get("lane"), entry.get("context") or {}
        key = bundle_key_of(str(lane), ctx)
        if lane not in LANES or key not in expected or expected[key] != lane:
            _refuse(GATE_UNKNOWN_LANE,
                    f"bundle {key!r} (lane={lane!r}) is not one of the {len(expected)} bundles "
                    f"derived from {conditions} x {sources}; it belongs to another release.")
        if key in seen:
            _refuse(GATE_DUPLICATE_BUNDLE,
                    f"bundle {key!r} appears twice: a duplicate silently fills a missing slot, "
                    "and the count still looks right.")

        full = _resolve_dir(entry.get("out_dir"), bundles_root, f"bundle {key!r}")
        files = entry.get("files")
        if not isinstance(files, dict) or ARM_BUNDLE_FILE not in files:
            _refuse(GATE_BUNDLE_BYTES_MOVED,
                    f"bundle {key!r} binds no {ARM_BUNDLE_FILE!r} in its files map; a bundle "
                    "nobody can address is a bundle nobody admitted.")
        # EVERY bound byte, re-hashed from disk. Not a sample: the file a forger edits is the
        # one nobody re-read.
        for rel, sha in sorted(files.items()):
            fpath = _safe_file(rel, full, f"bundle {key!r} file")
            if not os.path.isfile(fpath):
                _refuse(GATE_BUNDLE_BYTES_MOVED,
                        f"bundle {key!r} binds {rel!r}, which is not on disk.")
            got = file_sha256(fpath)
            if got != sha:
                _refuse(GATE_BUNDLE_BYTES_MOVED,
                        f"bundle {key!r}: {rel!r} hashes to {got[:16]}… but the manifest bound "
                        f"{str(sha)[:16]}…: the bytes changed after the verifier read them.")
        artifact_sha = stage2_content_sha256(files)
        if entry.get("artifact_sha256") != artifact_sha:
            _refuse(GATE_BUNDLE_BYTES_MOVED,
                    f"bundle {key!r} declares artifact_sha256="
                    f"{str(entry.get('artifact_sha256'))[:16]}… but its verified file map "
                    f"hashes to {artifact_sha[:16]}….")

        seen[key] = AdmittedBundle(
            bundle_key=key, bundle_id=str(entry.get("bundle_id")), lane=str(lane),
            path=str(entry["out_dir"]), raw_sha256=str(files[ARM_BUNDLE_FILE]),
            canonical_sha256=artifact_sha, files=dict(files),
            condition=ctx.get("condition"), from_condition=ctx.get("from_condition"),
            to_condition=ctx.get("to_condition"),
            pathway_source=ctx.get(NATIVE_PATHWAY_SOURCE_KEY))
        out.append((seen[key], full, entry))

    missing = sorted(set(expected) - set(seen))
    if missing:
        _refuse(GATE_MISSING_BUNDLE,
                f"the manifest is missing {len(missing)} bundle(s): {missing[:4]}. The release "
                f"is exactly {len(expected)} (3 Direct, 6 ordered temporal pairs, 6 pathway "
                "condition x source); a missing bundle is indistinguishable from one computed "
                "and found empty.", topology=True)
    ids = [b.bundle_id for b in seen.values()]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        _refuse(GATE_DUPLICATE_BUNDLE,
                f"bundle id(s) {dupes} appear more than once: one invocation repeated is not "
                "two, and a repeated result cannot stand in for a missing one.")
    return out


# --- 3. The arms, read from the bundle's OWN bytes. -------------------------- #
def load_bundle_arms(bundle: AdmittedBundle, full: str, entry: dict[str, Any], *,
                      provenance: dict[str, Any]) -> list[LoadedArm]:
    doc, _ = load_json(os.path.join(full, ARM_BUNDLE_FILE),
                        f"arm inventory of bundle {bundle.bundle_key!r}")
    arms: list[LoadedArm] = []
    for arm in (doc.get("arms") or ()):
        arm_key = str(arm.get("arm_key") or "")
        program_id, change = arm.get("program_id"), arm.get("desired_change")
        if not arm_key or not program_id or change not in DESIRED_CHANGES:
            _refuse(GATE_INCOMPLETE_TOPOLOGY,
                    f"bundle {bundle.bundle_key!r} carries an arm with no key, no program or "
                    f"an unknown desired_change: {arm.get('arm_key')!r} / {change!r}",
                    topology=True)
        binding = arm.get("ranking") or {}
        rpath = _safe_file(binding.get("path"), full, f"arm {arm_key!r} ranking")
        raw = file_sha256(rpath)
        if raw != binding.get("raw_sha256"):
            _refuse(GATE_BUNDLE_BYTES_MOVED,
                    f"arm {arm_key!r}: its ranking hashes to {raw[:16]}… but the bundle bound "
                    f"{str(binding.get('raw_sha256'))[:16]}….")
        ranking, _ = load_json(rpath, f"ranking of arm {arm_key!r}")
        rows = ranking.get("records")     # Stage-2's native reusable ranking rows
        if not isinstance(rows, list):
            _refuse(GATE_INCOMPLETE_TOPOLOGY,
                    f"arm {arm_key!r} binds a ranking with no `records` rows; an arm whose "
                    "ranking nobody can read is an arm nobody can replay.", topology=True)
        arms.append(LoadedArm(
            arm_key=arm_key, lane=bundle.lane, program_id=str(program_id),
            desired_change=str(change), bundle=bundle, ranking=dict(binding),
            provenance=dict(provenance, bundle_key=bundle.bundle_key,
                            bundle_id=bundle.bundle_id,
                            bundle_artifact_sha256=bundle.canonical_sha256),
            records=tuple(dict(r) for r in rows)))

    # THE MANIFEST'S INDEX MUST MATCH THE BUNDLE'S OWN BYTES. If the manifest's `arm_keys`
    # disagree with the arms the bundle ships, the index describes a bundle that is not there.
    declared = sorted(str(k) for k in (entry.get("arm_keys") or []))
    if declared != sorted(a.arm_key for a in arms):
        _refuse(GATE_ARM_INDEX_DISAGREES,
                f"bundle {bundle.bundle_key!r}: the manifest indexes {len(declared)} arm "
                f"key(s) but the bundle ships {len(arms)}; the index describes a bundle that "
                "is not on disk.")
    return arms


def check_arm_topology(arms: list[LoadedArm], bundles: list[AdmittedBundle],
                        programs: list[str]) -> tuple[str, ...]:
    """Every bundle x every program x both desired changes, each filled exactly once."""
    got = sorted({a.program_id for a in arms})
    if got != programs:
        _refuse(GATE_INCOMPLETE_TOPOLOGY,
                f"the release's arms resolve {len(got)} programs; its bound Stage-1 release "
                f"admits {len(programs)}. Programs are DERIVED from the release and CHECKED "
                "against the loaded arms; a disagreement means one of them is wrong about "
                "what this release contains.", topology=True)
    slots = {(a.bundle.bundle_key, a.program_id, a.desired_change) for a in arms}
    if len(slots) != len(arms):
        _refuse(GATE_INCOMPLETE_TOPOLOGY,
                "two arms occupy the same (bundle, program, desired_change) slot; a duplicate "
                "arm silently fills a missing one.", topology=True)
    expected = {(b.bundle_key, p, d)
                for b in bundles for p in programs for d in DESIRED_CHANGES}
    missing = sorted(expected - slots)
    if missing:
        _refuse(GATE_INCOMPLETE_TOPOLOGY,
                f"the release resolves {len(slots)} of {len(expected)} arm slots; "
                f"{len(missing)} are missing, e.g. {missing[:3]}. A partial release is never "
                "admissible.", topology=True)
    return tuple(programs)


