"""Source-provenance records, generated by a JSON serializer (never shell interpolation).

An earlier shell script built these by string-interpolating HTTP header values into a
heredoc; an ETag legitimately contains double-quotes (``"1571abc"``) and broke the JSON,
and every record embedded a ``/home/tcelab`` machine path. Both are structural hazards, so
provenance is emitted HERE, in Python, with ``json`` doing the escaping:

  * ``operational_record`` — the full, non-publishable record (may carry the local path);
    it belongs in a log OUTSIDE any release.
  * ``public_record`` / ``public_from_operational`` — the sanitized, publishable record:
    public URL, basename, hash, bytes, timestamps, publisher checksum — and NO machine path.
"""
from __future__ import annotations

import json
import os
from typing import Any, Optional


def parse_response_headers(text: str) -> dict[str, Optional[str]]:
    """Pull the fields we record. Values are kept VERBATIM (an ETag keeps its quotes)."""
    status = content_length = last_modified = etag = None
    for raw in text.splitlines():
        line = raw.strip("\r")
        if line.upper().startswith("HTTP/"):
            status = line
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        k = key.strip().lower()
        v = val.strip()
        if k == "content-length":
            content_length = v
        elif k == "last-modified":
            last_modified = v
        elif k == "etag":
            etag = v
    return {"http_status": status, "content_length": content_length,
            "last_modified": last_modified, "etag": etag}


def to_json(obj: Any) -> str:
    """Serialize with proper escaping. A value with a quote/tab/newline can never corrupt
    the document — ``json`` escapes it, unlike shell interpolation."""
    return json.dumps(obj, sort_keys=True, ensure_ascii=True, allow_nan=False)


def write_json(path: str, obj: Any) -> None:
    with open(path, "w") as fh:
        fh.write(to_json(obj))
    with open(path) as fh:            # parse-validate what was written
        json.load(fh)


def _basename(url: str) -> str:
    return url.rstrip("/").rsplit("/", 1)[-1]


def operational_record(*, name: str, url: str, headers: str, sha256: str,
                       size_bytes: int, accessed_start: str, accessed_end: str,
                       local_path: Optional[str] = None) -> dict[str, Any]:
    """Full operational record (non-publishable; may carry the local path)."""
    h = parse_response_headers(headers)
    rec = {
        "name": name, "url": url, "basename": _basename(url),
        "http_status": h["http_status"], "content_length_header": h["content_length"],
        "last_modified": h["last_modified"], "etag": h["etag"],
        "sha256": sha256, "size_bytes": size_bytes,
        "accessed_at_utc_start": accessed_start, "accessed_at_utc_end": accessed_end,
    }
    if local_path is not None:
        rec["local_path"] = local_path         # operational only; never in the public one
    return rec


def public_record(*, name: str, url: str, sha256: str, size_bytes: int,
                  last_modified: Optional[str], accessed_start: str, accessed_end: str,
                  publisher_checksum: Optional[str] = None) -> dict[str, Any]:
    """Sanitized, publishable record: public identifiers only, NO machine path."""
    return {
        "name": name, "url": url, "basename": _basename(url),
        "sha256": sha256, "size_bytes": size_bytes,
        "publisher_checksum": publisher_checksum, "last_modified": last_modified,
        "accessed_at_utc_start": accessed_start, "accessed_at_utc_end": accessed_end,
    }


def public_from_operational(op: dict[str, Any],
                            publisher_checksum: Optional[str] = None) -> dict[str, Any]:
    """Project an operational record to its publishable form (drops local_path)."""
    return public_record(
        name=op["name"], url=op["url"], sha256=op["sha256"],
        size_bytes=op["size_bytes"], last_modified=op.get("last_modified"),
        accessed_start=op["accessed_at_utc_start"],
        accessed_end=op["accessed_at_utc_end"], publisher_checksum=publisher_checksum)
