"""A sealed, NON-PRODUCTION Stage-2 aggregate in the CORRECT **NATIVE** shape, + the W3 receipt.

NOTHING HERE IS A SCIENTIFIC FINDING. Every program is ``FIXTURE_PROG_*``, every target
``FIXTURE_TGT_*``, every molecule ``FIXTURE_CHEMBL_*``, and every artifact declares
``artifact_class="fixture"`` — so ``stage2_aggregate.require_analysis`` and the v2 writer's store
firewall refuse these bytes by name on the analysis path. No candidate is invented anywhere.

WHY THIS FIXTURE EXISTS, AND WHAT IT REPLACES
---------------------------------------------
``tests/v2_fixture.py`` and ``tests/candidates_v2_fixture.py`` write the RETIRED aggregate schema
(``spot.stage02_aggregate_run_manifest.v1``, with an ``inventory[]`` and an ``admits{}`` block).
Stage 2 has never emitted one, and the native loader refuses them — which is why that family
errors at setup, and why nothing may be built on it.

The NATIVE contract, transcribed from Stage-2's actually-generated bytes:

    manifest  spot.stage02_run_manifest.v3_topology_only   top-level ``bundles[]``, each an
              all-arm bundle DIRECTORY (a bare ``out_dir`` NAME + a ``files{}`` map + arm_keys),
              a bound ``stage1_v3_release``, and a ``manifest_sha256`` that is the producer's
              SEMANTIC self-hash (content hash EXCLUDING created_at / manifest_sha256 / path).
    report    spot.stage02_run_manifest_verification.v1    a SEPARATE artifact from
              ``spot.stage02.run_manifest.verifier.v1``. Independence is the STRUCTURED FIELD
              ``generator_is_not_verifier`` — never a substring in a name.
    receipt   spot.stage02_stage3_receipt.v1               THE JOIN: it binds the aggregate
              manifest AND report AND the bridge, by raw AND canonical bytes.

    arm key   lane|program_id|desired_change|<context…>    the pole and the role are NEVER in it.

WHAT IS SYNTHETIC, AND WHAT IS REAL
-----------------------------------
The SCORES are synthetic. The SHAPE is real: the 15-bundle / 300-arm topology the admission gate
DERIVES from the release's own conditions and sources, the bare-``out_dir`` bundle directories,
the bound ranking files with their retained ``rank: null`` rows, and the semantic self-hash.

The ranking rows carry the typed fields W3's BRIDGE supplies (namespace, modality, modulation,
phenocopy class) — because the bridge consumer is not wired yet and this fixture stands in for
the post-bridge bytes. The modulation and phenocopy class are DERIVED from the frozen
``modality_contract`` tables rather than hand-written, exactly as the bridge derives them, so a
row here can never declare a direction its own ``arm_value`` does not imply.
"""
from __future__ import annotations

import json
import os
from typing import Any, Optional

from druglink import modality_contract as mc
from druglink import modality_rule as mr
from druglink import stage2_aggregate as sa
from druglink.stage2_contract import manifest_self_hash, stage2_content_sha256
from druglink.hashing import file_sha256

# 10 programs, named so nothing can be special-cased. The CONDITIONS and SOURCES are the
# release's own — the loader DERIVES the topology from them and refuses any other release.
PROGRAMS = tuple(f"FIXTURE_PROG_{i:02d}" for i in range(sa.N_PROGRAMS))
CONDITIONS = sa.CONDITIONS
SOURCES = sa.PATHWAY_SOURCES

MANIFEST_NAME = "stage2_run_manifest.json"
REPORT_NAME = "stage2_aggregate_verification.json"
RECEIPT_NAME = "stage2_stage3_receipt.json"
STAGE1_NAME = "stage01_v3_release.json"

NS_ENSEMBL = mc.W3_NS_ENSEMBL_GENE_ID
NS_SYMBOL = mc.W3_NS_GENE_SYMBOL
MODALITY = mc.MODALITY_CRISPRI

# The phenocopy vocabulary W3 serializes, keyed by the modulation the sign implies. Restated from
# the bridge contract; the row DERIVES its class rather than declaring one.
PHENOCOPY_CLASS_OF = {
    mc.MOD_DECREASE: "inhibition_observed_compatible",
    mc.MOD_INCREASE: "inhibitor_opposed",
    mc.MOD_NO_DIRECTION: "no_directional_response",
    mc.MOD_NOT_EVALUATED: "not_evaluable",
}

# The five targets, each exercising a different disposition against the sealed store. `base` is
# the arm value of the ``increase`` arm; the ``decrease`` arm is its EXACT sign transform, which
# is what Stage 2 does — the two arms of a program in a context are two logical arms over ONE
# measured base effect, and they can never disagree about a magnitude they share.
#                target_id           namespace     base   evaluable  rank
TARGETS: tuple[tuple[str, str, float, bool, Optional[int]], ...] = (
    ("FIXTURE_TGT_00", NS_ENSEMBL, 0.42, True, 1),      # in store; inhibitors + a binder
    ("FIXTURE_TGT_01", NS_ENSEMBL, -0.31, True, None),  # RETAINED with rank:null. Never a 0.
    ("FIXTURE_TGT_02", NS_ENSEMBL, 0.15, True, 2),      # in store; only ambiguous assertions
    ("FIXTURE_TGT_SYM", NS_SYMBOL, 0.0, False, None),   # not evaluable; unreachable namespace
    ("FIXTURE_TGT_OFF", NS_ENSEMBL, 0.20, True, 3),     # NOT in the admitted typed universe
)


def _write(path: str, doc: Any) -> str:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(json.dumps(doc, sort_keys=True, separators=(",", ":")))
    return path


def arm_key(lane: str, program: str, change: str, ctx: dict[str, str]) -> str:
    """Stage-2's canonical reusable key. Restated here so the fixture cannot borrow the code
    under test to build the very keys that code is being asked to derive."""
    if lane == sa.LANE_DIRECT:
        tail = [ctx["condition"]]
    elif lane == sa.LANE_TEMPORAL:
        tail = [ctx["from_condition"], ctx["to_condition"]]
    else:
        tail = [ctx["condition"], ctx["gene_set_source"]]
    return "|".join([lane, program, change] + tail)


def _contexts() -> list[tuple[str, str, dict[str, str]]]:
    """(bundle_key, lane, native context). 3 Direct + 6 ordered temporal pairs + 6 pathway."""
    out = [(f"{sa.LANE_DIRECT}|{c}", sa.LANE_DIRECT, {"condition": c}) for c in CONDITIONS]
    out += [(f"{sa.LANE_TEMPORAL}|{a}|{b}", sa.LANE_TEMPORAL,
             {"from_condition": a, "to_condition": b})
            for a, b in sa.ordered_condition_pairs(CONDITIONS)]
    out += [(f"{sa.LANE_PATHWAY}|{c}|{s}", sa.LANE_PATHWAY,
             {"condition": c, "gene_set_source": s})
            for c in CONDITIONS for s in SOURCES]
    return out


def _measured_records(change: str) -> list[dict[str, Any]]:
    """The typed ranking rows, post-bridge. The DIRECTION is derived from the SIGN, never
    declared: a row cannot claim a modulation its own arm_value does not imply."""
    rows = []
    for target_id, namespace, base, evaluable, rank in TARGETS:
        # The arm value is PRE-ORIENTED to its own arm's desired_change by Stage 2. `increase` is
        # the base; `decrease` is its exact negation (0.0 negates to 0.0, never -0.0).
        value = base if change == "increase" else (0.0 if base == 0 else -base)
        sign = mr.observed_sign_state(value, evaluable=evaluable, origin_is_measured=True,
                                      arm_key="fixture")
        modulation = mc.MODULATION_FOR[(MODALITY, sign)]
        rows.append({
            "target_id": target_id,
            "target_id_namespace": namespace,
            "arm_value": value,
            "evaluable": evaluable,
            # A RETAINED row with no rank. It stays null all the way to the edge: never 0,
            # never last, never invented.
            "rank": rank,
            "observed_perturbation_modality": MODALITY,
            "desired_target_modulation": modulation,
            "phenocopy_class": PHENOCOPY_CLASS_OF[modulation],
        })
    return rows


def _pathway_records(source: str) -> list[dict[str, Any]]:
    """A gene-set ENRICHMENT record. It carries NO target_id, NO arm_value, NO rank and NO
    modality — a pathway record is a statement about a SET, and a context that wore a target's
    clothes would let a gene set be prescribed a drug."""
    return [{
        "pathway_id": f"{source}:FIXTURE_SET_1",
        "pathway_source": source,
        "enrichment_value": 0.5,
        "coverage": 0.25,
        "convergence": "fixture_convergence_ref",
        "leading_edge": [{"target_id": t, "target_id_namespace": ns}
                         for t, ns, *_ in TARGETS[:3]],
    }]


def _bundle(key: str, lane: str, ctx: dict[str, str], out_dir: str,
            root: str) -> dict[str, Any]:
    """One all-arm bundle DIRECTORY: arm_bundle.json + one bound ranking file per arm."""
    full = os.path.join(root, lane, out_dir)
    files: dict[str, str] = {}
    arms = []
    for program in PROGRAMS:
        for change in sa.DESIRED_CHANGES:
            records = (_pathway_records(ctx["gene_set_source"])
                       if lane == sa.LANE_PATHWAY else _measured_records(change))
            rel = f"rankings/{program}__{change}.json"
            path = _write(os.path.join(full, rel), {"records": records})
            files[rel] = file_sha256(path)
            arms.append({
                "arm_key": arm_key(lane, program, change, ctx),
                "program_id": program,
                "desired_change": change,
                "ranking": {"path": rel, "raw_sha256": files[rel],
                            "canonical_sha256": stage2_content_sha256(
                                {"records": records})},
            })
    bundle_path = _write(os.path.join(full, sa.ARM_BUNDLE_FILE), {
        "schema_version": "spot.stage02_arm_bundle.v1",
        "artifact_class": "fixture", "lane": lane, "context": dict(ctx),
        "bundle_id": f"FIXTURE-{key.replace('|', '-')}",
        "n_arms": len(arms), "arms_are_independent": True, "arms": arms})
    files[sa.ARM_BUNDLE_FILE] = file_sha256(bundle_path)
    return {
        "bundle_id": f"FIXTURE-{key.replace('|', '-')}",
        "lane": lane,
        "context": dict(ctx),
        "out_dir": out_dir,
        "files": files,
        "artifact_sha256": stage2_content_sha256(files),
        "arm_keys": sorted(a["arm_key"] for a in arms),
        "n_arms": len(arms),
    }


def build(root: str, *, mutate_manifest=None, mutate_report=None, mutate_receipt=None,
          reseal: bool = True) -> dict[str, str]:
    """Materialise the sealed NATIVE release and return the paths Stage 3 admits it from."""
    root = str(root)
    bundles_root = os.path.join(root, "bundles")

    stage1 = {"schema_version": "spot.stage01_v3_release.v1",
              "release_id": "FIXTURE_STAGE1_V3",
              "programs": list(PROGRAMS), "conditions": list(CONDITIONS),
              "gene_set_sources": list(SOURCES)}
    stage1_path = _write(os.path.join(root, STAGE1_NAME), stage1)

    bundles = [_bundle(key, lane, ctx, f"FIXTURE-{key.replace('|', '-')}", bundles_root)
               for key, lane, ctx in _contexts()]

    manifest: dict[str, Any] = {
        "schema_version": sa.MANIFEST_SCHEMA,
        "manifest_id": "FIXTURE_RUN",
        "created_at": "2026-07-13T00:00:00+00:00",       # OUTSIDE the semantic self-hash
        "conditions": list(CONDITIONS),
        "gene_set_sources": list(SOURCES),
        "stage1_v3_release": {
            "programs": list(PROGRAMS),
            "conditions": list(CONDITIONS),
            "gene_set_sources": list(SOURCES),
            "release_canonical_sha256": stage2_content_sha256(stage1),
            "release_raw_sha256": file_sha256(stage1_path),
            "registry_scorer_view_canonical_sha256": stage2_content_sha256(
                {"fixture_registry_scorer_view": True}),
        },
        "bundles": bundles,
        "n_bundles": len(bundles),
        "n_bound_arm_slots": sum(b["n_arms"] for b in bundles),
        "n_expected_arm_slots": sa.N_ARM_SLOTS,
        "topology_complete": True,
        # PUBLISHED by the producer, and INDEPENDENTLY re-derived by Stage 3. If the two ever
        # disagree, every arm key Stage 3 derives is for the opposite perturbation.
        "arm_key_rule": ("lane|program_id|desired_change|context — the pole direction and the "
                         "role are PROVENANCE on the arm, never its identity"),
        "desired_change_by_role_and_pole": {
            "away_from_A|high": "decrease", "away_from_A|low": "increase",
            "toward_B|high": "increase", "toward_B|low": "decrease"},
        "combined_objective": None,
        "combined_objective_permitted": False,
        "emits_p_q_or_fdr": False,
    }
    if mutate_manifest:
        mutate_manifest(manifest)
    if reseal:
        manifest[sa.SELF_HASH_FIELD] = manifest_self_hash(manifest)
    manifest_path = _write(os.path.join(root, MANIFEST_NAME), manifest)
    self_hash = manifest[sa.SELF_HASH_FIELD]

    report: dict[str, Any] = {
        "schema_version": sa.REPORT_SCHEMA,
        "verifier_id": sa.AGGREGATE_VERIFIER_ID,
        # Independence is a STRUCTURED FIELD, not a substring in a name.
        "generator_is_not_verifier": True,
        "verdict": sa.ADMIT,
        "n_failed": 0,
        "failed_gates": [],
        "topology_complete": True,
        "release_admissible": True,
        "admission": {"status": sa.ADMITTED},
        sa.SELF_HASH_FIELD: self_hash,
        "manifest_sha256_recomputed": self_hash,
    }
    if mutate_report:
        mutate_report(report)
    report_path = _write(os.path.join(root, REPORT_NAME), report)

    # THE JOIN. The bridge is not consumed here (its loader is W16's), but the receipt must BIND
    # one: a receipt that binds only the aggregate would let an ADMIT travel with a handoff it
    # was never about.
    bridge = {"schema_version": "spot.stage02_stage3_bridge.v1", "fixture": True}
    receipt: dict[str, Any] = {
        "schema_version": "spot.stage02_stage3_receipt.v1",
        "aggregate": {
            "manifest": {"raw_sha256": file_sha256(manifest_path),
                         "canonical_sha256": stage2_content_sha256(manifest)},
            "report": {"raw_sha256": file_sha256(report_path),
                       "canonical_sha256": stage2_content_sha256(report)},
        },
        "bridge": {"raw_sha256": stage2_content_sha256({"raw": bridge}),
                   "canonical_sha256": stage2_content_sha256(bridge)},
    }
    if mutate_receipt:
        mutate_receipt(receipt)
    receipt_path = _write(os.path.join(root, RECEIPT_NAME), receipt)

    return {"manifest": manifest_path, "report": report_path, "receipt": receipt_path,
            "bundles_root": bundles_root, "stage1_release": stage1_path,
            "manifest_doc": manifest}


def admit(paths: dict[str, str]) -> sa.AdmittedAggregate:
    """The sealed release, through the REAL native admission gate. No shortcut, no fallback."""
    return sa.admit_aggregate(manifest_path=paths["manifest"], report_path=paths["report"],
                              bundles_root=paths["bundles_root"],
                              stage1_release_path=paths["stage1_release"])
