"""The REAL Stage-2 aggregate release. TRANSCRIBED FROM GENERATED BYTES, never hand-written.

The honest release Stage-3's tests parse is made of:

  * the REAL aggregate manifest and the REAL aggregate verification report, copied VERBATIM
    from W3's generated native-contract handoff — every byte of both was produced by Stage-2's
    actual ``run_release`` / ``verify_run_manifest`` CLIs and admitted end-to-end (verdict
    ``admit``, ``n_failed: 0``, 15 bundles / 300 arm slots);
  * the 15 all-arm bundle DIRECTORIES, which the handoff does not ship (it carries only the 8
    root artifacts plus one example bundle per lane). They are regenerated by Stage-2's own
    bundle builder — and the real manifest's OWN ``files{}`` hashes and ``artifact_sha256``
    then PROVE they are the same bytes it bound. We do not have to trust the regeneration:
    if it drifted by one byte the loader would refuse it, and these tests would fail;
  * the authoritative Stage-1 v3 release, staged FROM GIT. Its canonical hash is exactly the
    ``release_canonical_sha256`` the real manifest pins — the manifest itself says so.

THIS IS THE WHOLE POINT. What this replaces was a hand-written fixture in a schema Stage 2
never had (``inventory[]``, ``admits{}``, top-level ``artifact_class``, a verifier id
containing "independent"). It passed 34 tests because one author wrote both the loader and
the fixture it parsed. A fixture that can drift from the producer without a test failing is
how that happens; this one cannot.

The bundle SCORES are Stage-2 fixtures (synthetic — no science is asserted). The schema, the
counts, the self-hash and the ADMISSION are real.

If the generated handoff or the Stage-2 builder is not reachable on this host, the tests
SKIP. There is no fallback: fabricating the shape is the defect, not the workaround.
"""
from __future__ import annotations

import json
import os
import shutil
import sys
from typing import Any, Callable, Optional

import pytest

# --- The REAL generated bytes, and the builder for the bundles they bind. ---- #
_DEFAULT_CONTRACT = ("/home/tcelab/.spot-runs/20260712T021343Z/W3_NATIVE_CONTRACT")
_DEFAULT_W3 = "/home/tcelab/worktrees/spot-stage2-w3/02_geneskew"

NATIVE_CONTRACT = os.environ.get("SPOT_W3_NATIVE_CONTRACT", _DEFAULT_CONTRACT)
STAGE2_ROOT = os.environ.get("SPOT_STAGE2_W3", _DEFAULT_W3)

REAL_MANIFEST = os.path.join(NATIVE_CONTRACT, "release_root", "stage2_run_manifest.json")
REAL_REPORT = os.path.join(NATIVE_CONTRACT, "release_root",
                           "stage2_aggregate_verification.json")

SKIP_REASON = (
    "the REAL Stage-2 generated native contract is not on this host (looked in "
    f"{NATIVE_CONTRACT!r} and {STAGE2_ROOT!r}; set SPOT_W3_NATIVE_CONTRACT / SPOT_STAGE2_W3 "
    "to override). Stage-3's aggregate tests parse Stage-2's ACTUAL generated bytes — they "
    "never hand-write a Stage-2 document, because a hand-written fixture in an invented "
    "schema is the exact defect these tests exist to prevent."
)


def _bundle_builder():
    """Stage-2's OWN bundle builder, for the 15 dirs the handoff does not ship."""
    analysis = os.path.join(STAGE2_ROOT, "analysis")
    tests = os.path.join(STAGE2_ROOT, "tests", "direct")
    if not (os.path.isfile(REAL_MANIFEST) and os.path.isfile(REAL_REPORT)
            and os.path.isfile(os.path.join(analysis, "direct", "run_manifest.py"))):
        pytest.skip(SKIP_REASON)
    for p in (analysis, tests):
        if p not in sys.path:
            sys.path.insert(0, p)
    try:
        import fixtures_run_manifest as F
    except ImportError as exc:                       # pragma: no cover - host-dependent
        pytest.skip(f"{SKIP_REASON} (import failed: {exc})")
    return F


def _reseal(doc: dict[str, Any]) -> dict[str, Any]:
    """Re-seal a manifest a test deliberately forged.

    Uses Stage-3's re-derivation of the producer's semantic self-hash rule — because a forger
    with repo access has that rule too, and an attack that could not re-seal would be no
    attack at all. The gates must stop a CONSISTENT forgery, not a careless one.
    """
    from druglink.stage2_aggregate import manifest_self_hash
    doc["manifest_sha256"] = manifest_self_hash(doc)
    return doc


def _write(path: str, doc: Any) -> str:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, sort_keys=True)
        fh.write("\n")
    return path


def build_release(
    root: Any,
    *,
    mutate_bundles: Optional[Callable[[str], None]] = None,
    mutate_manifest: Optional[Callable[[dict], None]] = None,
    reseal_manifest: bool = True,
    reforge_admission: bool = False,
    mutate_report: Optional[Callable[[dict], None]] = None,
    mutate_disk: Optional[Callable[[dict], None]] = None,
    second_manifest: bool = False,
) -> dict[str, str]:
    """Materialise the REAL release and return Stage-3's four explicit admission paths.

    The four paths are bound EXPLICITLY — Stage-2's ``stage3_inputs`` receipt is defined in
    its source but is ABSENT from the generated report, and Stage 3 does not bind fields the
    real producer does not emit.

      mutate_bundles(bundles_root)  tamper bundle bytes the real manifest bound
      mutate_manifest(doc)          forge the manifest (RE-SEALED by default, as a forger
                                    with repo access would; reseal_manifest=False leaves the
                                    self-hash stale)
      reforge_admission             ALSO re-point the report's manifest_sha256 /
                                    manifest_sha256_recomputed at the forged manifest — the
                                    STRONGEST attack, in which the forger owns BOTH files and
                                    the whole hash chain closes. It exists so the gates that
                                    re-derive the topology from the BUNDLES and the RELEASE
                                    are reachable: without it every manifest edit dies at the
                                    report binding, and the deeper gates go untested.
      mutate_report(doc)            forge the admission itself
      mutate_disk(paths)            move bytes / repoint paths
    """
    F = _bundle_builder()
    root = str(root)
    os.makedirs(root, exist_ok=True)

    # 1) The REAL Stage-1 v3 release (staged from git) + the 15 bundle dirs the real manifest
    #    binds, rebuilt by Stage-2's own builder. The manifest's hashes prove they are right.
    run = F.complete_run(root)

    # 2) The REAL manifest and the REAL admission report — copied VERBATIM. Not re-derived,
    #    not re-serialised: these are the generated bytes, exactly as Stage 2 emitted them.
    manifest_path = os.path.join(root, "stage2_run_manifest.json")
    report_path = os.path.join(root, "stage2_aggregate_verification.json")
    shutil.copyfile(REAL_MANIFEST, manifest_path)
    shutil.copyfile(REAL_REPORT, report_path)

    if mutate_bundles:
        mutate_bundles(run["root"])
    if mutate_manifest:
        doc = json.load(open(manifest_path))
        mutate_manifest(doc)
        _write(manifest_path, _reseal(doc) if reseal_manifest else doc)
    if reforge_admission:
        sealed = json.load(open(manifest_path))["manifest_sha256"]
        doc = json.load(open(report_path))
        doc["manifest_sha256"] = doc["manifest_sha256_recomputed"] = sealed
        _write(report_path, doc)
    if mutate_report:
        doc = json.load(open(report_path))
        mutate_report(doc)
        _write(report_path, doc)

    # A SECOND, byte-different manifest the real report never admitted.
    other_path = os.path.join(root, "other_run_manifest.json")
    if second_manifest:
        doc = json.load(open(manifest_path))
        doc["conditions"] = list(reversed(doc["conditions"]))   # a different release order
        _write(other_path, _reseal(doc))

    paths = {"manifest_path": manifest_path, "report_path": report_path,
             "bundles_root": run["root"],
             "stage1_release_path": run["release_path"]}
    if second_manifest:
        paths["other_manifest_path"] = other_path
    if mutate_disk:
        mutate_disk(paths)
    return paths


# --- The retired INVENTED shape, kept ONLY so a test can prove it is refused. - #
# This is what Stage-3 used to emit and parse: `inventory[]` instead of `bundles[]`, an
# `admits{}` block instead of the report's own manifest_sha256, a top-level `artifact_class`
# Stage 2 has never declared, and a verifier id chosen to contain the word "independent".
# Every field here is fiction. It exists so the loader can be pointed at it and REFUSE.
INVENTED_MANIFEST_SCHEMA = "spot.stage02_aggregate_run_manifest.v1"
INVENTED_REPORT_SCHEMA = "spot.stage02_aggregate_verification.v1"
INVENTED_VERIFIER_ID = "spot.stage02.aggregate.independent_verifier.v1"


def build_invented_release(root: Any) -> dict[str, str]:
    """Write the OLD invented shape. The loader must refuse it, by name."""
    root = str(root)
    bundles_root = os.path.join(root, "bundles")
    os.makedirs(bundles_root, exist_ok=True)

    stage1 = _write(os.path.join(root, "stage1_release.json"),
                    {"release_id": "invented_stage1_v3"})
    manifest = {
        "schema_version": INVENTED_MANIFEST_SCHEMA,
        "artifact_class": "analysis",                 # Stage 2 declares no artifact_class
        "generated_at": "2026-07-13T00:00:00Z",
        "stage1_release": {"release_id": "invented_stage1_v3",
                           "raw_sha256": "0" * 64},   # not how Stage 2 pins its release
        "inventory": [],                              # Stage 2 emits `bundles[]`, never this
    }
    manifest_path = _write(os.path.join(root, "aggregate_run_manifest.json"),
                           _reseal(manifest))
    report_path = _write(os.path.join(root, "aggregate_verification.json"), {
        "schema_version": INVENTED_REPORT_SCHEMA,
        "verifier_id": INVENTED_VERIFIER_ID,          # the "independent" substring: not a gate
        "verdict": "admit",
        "admits": {"manifest_raw_sha256": "0" * 64,   # Stage 2 emits no `admits{}` block
                   "manifest_canonical_sha256": "0" * 64},
    })
    return {"manifest_path": manifest_path, "report_path": report_path,
            "bundles_root": bundles_root, "stage1_release_path": stage1}
