"""THE BRIDGE CONSUMER, under attack. Every gate must FIRE on a CONSISTENT forgery.

The bridge, its report and its receipt here are generated by driving **W3's REAL producer and
their REAL independent verifiers** (``tests/w3_bridge_fixture``). Nothing is hand-authored: a
hand-written fixture is how Stage 3 once invented an entire Stage-2 manifest schema and tested
itself against its own fiction.

NON-VACUITY. Every attack first asserts that the UNTOUCHED release ADMITS, with rows on both
sides — a gate that fires on an empty bridge has proved nothing.

Each forgery is RE-SEALED (``reseal_bridge`` / ``reseal_receipt``), because a forger with repo
access can recompute a self-hash. The gates must stop a CONSISTENT forgery, not a careless one.
"""
from __future__ import annotations

import json
import os
import shutil

import pytest
import w3_bridge_fixture as W3F
from druglink import stage2_aggregate as sa
from druglink import stage2_bridge as sb


@pytest.fixture(scope="module")
def release(tmp_path_factory):
    """ONE admitted release + bridge, built once by W3's real producers. Attacks work on copies."""
    return W3F.build_release(str(tmp_path_factory.mktemp("w3_release")))


@pytest.fixture()
def forged(release, tmp_path):
    """A private copy of the whole release, so an attack cannot leak into another test."""
    root = str(tmp_path / "release")
    shutil.copytree(os.path.dirname(release["bundles_root"]), root)
    bundles = os.path.join(root, os.path.basename(release["bundles_root"]))
    return {"bundles_root": bundles,
            "stage2_manifest": os.path.join(bundles, W3F.MANIFEST_FILE),
            "stage2_report": os.path.join(bundles, W3F.AGGREGATE_REPORT_FILE),
            "stage1_release": release["stage1_release"].replace(
                os.path.dirname(release["bundles_root"]), root),
            "stage2_bridge": os.path.join(bundles, W3F.BRIDGE_FILE),
            "stage2_bridge_report": os.path.join(bundles, W3F.BRIDGE_REPORT_FILE),
            "stage2_bridge_receipt": os.path.join(bundles, W3F.RECEIPT_FILE)}


def _aggregate(paths, artifact_class="analysis"):
    return sa.admit_aggregate(
        manifest_path=paths["stage2_manifest"], report_path=paths["stage2_report"],
        bundles_root=paths["bundles_root"], stage1_release_path=paths["stage1_release"],
        artifact_class=artifact_class)


def _admit(paths, aggregate=None):
    aggregate = aggregate or _aggregate(paths)
    return sa.admit_bridge(
        bridge_path=paths["stage2_bridge"], report_path=paths["stage2_bridge_report"],
        receipt_path=paths["stage2_bridge_receipt"], aggregate=aggregate,
        aggregate_report_path=paths["stage2_report"])


def _refuses(paths, gate, aggregate=None):
    with pytest.raises(sa.Stage2BridgeError, match=gate) as exc:
        _admit(paths, aggregate)
    return exc.value


# --------------------------------------------------------------------------- #
# NON-VACUITY. The untouched release admits, and there is real evidence on BOTH sides.
# --------------------------------------------------------------------------- #
class TestTheUntouchedReleaseAdmits:
    def test_the_bridge_admits_and_carries_real_rows_over_real_native_records(self, forged):
        aggregate = _aggregate(forged)
        native = sb.native_index(aggregate)
        bridge = _admit(forged, aggregate)

        assert len(native) > 0, "the native bytes carry no rows: every gate below would be vacuous"
        assert bridge.n_rows == len(native), (
            "the bridge must carry EXACTLY the rows the admitted native bytes produce")
        assert bridge.n_rows >= 1000 and bridge.n_pathway_contexts > 0
        assert bridge.verdict == "admit"

    def test_every_typed_row_ADDS_a_namespace_and_a_modality_the_native_rows_lack(self, forged):
        aggregate = _aggregate(forged)
        native = sb.native_index(aggregate)
        # the native record states the measurement, and NOTHING about identity or assay
        one = next(iter(native.values()))
        assert set(one) == {"target_id", "arm_value", "evaluable", "rank"}

        typed = sa.typed_aggregate(aggregate, _admit(forged, aggregate))
        rows = [r for a in typed.arms if a.lane in sa.MEASURED_LANES for r in a.records]
        assert rows
        assert {r["target_id_namespace"] for r in rows} <= {"ensembl_gene_id", "gene_symbol"}
        assert {r["observed_perturbation_modality"] for r in rows} == {"CRISPRi_knockdown"}
        # ...and it carries the identity of the bridge that typed it
        assert typed.bridge_binding["bridge_raw_sha256"]

    def test_the_universe_is_HETEROGENEOUS_so_a_shape_guess_would_mistype_it(self, forged):
        typed = sa.typed_aggregate(_aggregate(forged), _admit(forged))
        rows = [r for a in typed.arms if a.lane in sa.MEASURED_LANES for r in a.records]
        namespaces = {r["target_id_namespace"] for r in rows}
        assert namespaces == {"ensembl_gene_id", "gene_symbol"}, (
            "the fixture must carry BOTH namespaces: a namespace guessed from an id's shape "
            "mistypes exactly the bare symbols, and three of the four carry an ENSG-looking key "
            "belonging to a DIFFERENT gene")


# --------------------------------------------------------------------------- #
# THE MUTATION ATTACKS. Each one is a NAMED refusal that FIRES.
# --------------------------------------------------------------------------- #
class TestTheBridgeBytes:
    def test_bridge_bytes_edited_after_sealing(self, forged):
        doc = json.load(open(forged["stage2_bridge"]))
        doc["n_target_rows"] = 1                      # edited, and NOT re-sealed
        with open(forged["stage2_bridge"], "w") as fh:
            json.dump(doc, fh)
        _refuses(forged, sb.GATE_BRIDGE_SELF_HASH)

    def test_a_bridge_that_binds_nothing(self, forged):
        W3F.reseal_bridge(forged["stage2_bridge"],
                          lambda d: d["bindings"].pop("aggregate"))
        _refuses(forged, sb.GATE_BRIDGE_BINDS_NOTHING)

    def test_a_CONSISTENT_reseal_still_fails_the_report_that_judged_the_old_bytes(self, forged):
        """The forger re-seals perfectly. The REPORT still names the bytes it actually judged."""
        W3F.reseal_bridge(forged["stage2_bridge"],
                          lambda d: d["target_rows"][0].update({"arm_value": -99.0}))
        _refuses(forged, sb.GATE_REPORT_JUDGED_OTHER_BYTES)


class TestTheReportAndTheReceipt:
    def test_the_report_is_swapped_for_one_that_judged_another_bridge(self, forged):
        W3F.rewrite(forged["stage2_bridge_report"],
                    lambda d: d["judged_bridge"].update({"raw_sha256": "0" * 64}))
        _refuses(forged, sb.GATE_REPORT_JUDGED_OTHER_BYTES)

    def test_a_report_that_did_not_admit(self, forged):
        W3F.rewrite(forged["stage2_bridge_report"],
                    lambda d: d.update({"verdict": "reject", "n_failed": 1}))
        _refuses(forged, sb.GATE_REPORT_NOT_ADMIT)

    def test_THE_RECEIPT_IS_ABSENT__a_report_alone_names_no_bytes(self, forged):
        os.remove(forged["stage2_bridge_receipt"])
        _refuses(forged, sb.GATE_RECEIPT_ABSENT)

    def test_the_receipt_is_swapped_for_one_that_names_another_bridge(self, forged):
        W3F.reseal_receipt(forged["stage2_bridge_receipt"],
                           lambda d: d["bridge"].update({"raw_sha256": "0" * 64}))
        _refuses(forged, sb.GATE_RECEIPT_BINDS_OTHER_BYTES)

    def test_the_receipt_names_another_aggregate(self, forged):
        W3F.reseal_receipt(forged["stage2_bridge_receipt"],
                           lambda d: d["aggregate"]["manifest"].update({"raw_sha256": "0" * 64}))
        _refuses(forged, sb.GATE_RECEIPT_BINDS_OTHER_BYTES)

    def test_the_receipt_is_edited_and_not_resealed(self, forged):
        doc = json.load(open(forged["stage2_bridge_receipt"]))
        doc["aggregate_was_resealed"] = True
        with open(forged["stage2_bridge_receipt"], "w") as fh:
            json.dump(doc, fh)
        _refuses(forged, sb.GATE_RECEIPT_SELF_HASH)


class TestTheAggregateCrossBind:
    def test_a_bridge_built_over_a_DIFFERENT_aggregate(self, forged):
        """Every self-hash inside the chain agrees. It is simply not THIS release's bridge."""
        other = "a" * 64
        W3F.reseal_bridge(
            forged["stage2_bridge"],
            lambda d: d["bindings"]["aggregate"]["manifest"].update({"raw_sha256": other}))
        # ...and the forger re-points the report and the receipt at the resealed bridge, so the
        # ONLY thing left standing between them and an admit is the cross-bind.
        raw = sb.canonical_sha256  # noqa: F841  (documents the rule the fixture re-seals under)
        import hashlib
        with open(forged["stage2_bridge"], "rb") as fh:
            bridge_raw = hashlib.sha256(fh.read()).hexdigest()
        W3F.rewrite(forged["stage2_bridge_report"],
                    lambda d: d["judged_bridge"].update({"raw_sha256": bridge_raw}))
        W3F.reseal_receipt(forged["stage2_bridge_receipt"],
                           lambda d: d["bridge"].update({"raw_sha256": bridge_raw}))
        exc = _refuses(forged, sb.GATE_RECEIPT_BINDS_OTHER_BYTES)
        assert "canonical" in str(exc) or "bridge" in str(exc)

    def test_the_bridge_names_the_aggregate_stage3_admitted(self, forged):
        aggregate = _aggregate(forged)
        bound = json.load(open(forged["stage2_bridge"]))["bindings"]["aggregate"]["manifest"]
        assert bound["raw_sha256"] == aggregate.manifest_raw_sha256


class TestTheRowsAgainstTheNativeBytes:
    """THE RULE: the bridge may ADD what the native bytes lack; it may never CHANGE what they say."""

    def test_a_row_that_CHANGES_the_native_arm_value(self, forged):
        W3F.reseal_bridge(
            forged["stage2_bridge"],
            lambda d: d["target_rows"][0].update(
                {"arm_value": -0.5, "desired_target_modulation": "increase",
                 "phenocopy_class": "inhibitor_opposed"}))
        # the report is re-pointed too, so the COHERENT reseal is fully consistent...
        _repoint(forged)
        _refuses(forged, sb.GATE_ROW_CHANGES_A_NATIVE_FACT)

    def test_a_row_that_CHANGES_the_native_rank(self, forged):
        W3F.reseal_bridge(forged["stage2_bridge"],
                          lambda d: d["target_rows"][0].update({"rank": 9999}))
        _repoint(forged)
        _refuses(forged, sb.GATE_ROW_CHANGES_A_NATIVE_FACT)

    def test_a_row_whose_IDENTITY_namespace_was_altered(self, forged):
        W3F.reseal_bridge(
            forged["stage2_bridge"],
            lambda d: d["target_rows"][0].update({"target_id_namespace": "hgnc_symbol"}))
        _repoint(forged)
        _refuses(forged, sb.GATE_ROW_IDENTITY_NOT_TYPED)

    def test_a_row_whose_MODALITY_was_changed(self, forged):
        W3F.reseal_bridge(
            forged["stage2_bridge"],
            lambda d: d["target_rows"][0].update(
                {"observed_perturbation_modality": "CRISPRa_activation"}))
        _repoint(forged)
        _refuses(forged, sb.GATE_ROW_MODALITY_NOT_DECLARED)

    def test_a_row_whose_MODALITY_is_ABSENT(self, forged):
        W3F.reseal_bridge(
            forged["stage2_bridge"],
            lambda d: d["target_rows"][0].pop("observed_perturbation_modality"))
        _repoint(forged)
        _refuses(forged, sb.GATE_ROW_MODALITY_NOT_DECLARED)

    def test_the_serialized_modulation_disagrees_with_the_sign_re_derived_from_arm_value(
            self, forged):
        """The ONE inversion this whole module exists to make impossible."""
        W3F.reseal_bridge(
            forged["stage2_bridge"],
            lambda d: d["target_rows"][0].update({"desired_target_modulation": "increase"}))
        _repoint(forged)
        _refuses(forged, sb.GATE_MODULATION_DISAGREES_WITH_SIGN)

    def test_an_ORPHAN_row_the_native_bytes_do_not_produce(self, forged):
        def add(doc):
            row = dict(doc["target_rows"][0])
            row["target_id"] = "ENSG99999999999"
            doc["target_rows"].append(row)
        W3F.reseal_bridge(forged["stage2_bridge"], add)
        _repoint(forged)
        _refuses(forged, sb.GATE_ROW_ORPHAN)

    def test_a_DROPPED_row_the_native_bytes_do_produce(self, forged):
        W3F.reseal_bridge(forged["stage2_bridge"], lambda d: d["target_rows"].pop(0))
        _repoint(forged)
        _refuses(forged, sb.GATE_ROW_DROPPED)

    def test_a_DUPLICATE_row_double_counts_its_own_evidence(self, forged):
        W3F.reseal_bridge(forged["stage2_bridge"],
                          lambda d: d["target_rows"].append(dict(d["target_rows"][0])))
        _repoint(forged)
        _refuses(forged, sb.GATE_DUPLICATE_BRIDGE_ROW)

    def test_a_TYPED_ROW_ON_THE_PATHWAY_LANE(self, forged):
        def add(doc):
            row = dict(doc["target_rows"][0])
            row["lane"] = "pathway"
            doc["target_rows"].append(row)
        W3F.reseal_bridge(forged["stage2_bridge"], add)
        _repoint(forged)
        _refuses(forged, sb.GATE_PATHWAY_SOURCED_A_TYPED_ROW)


class TestThePathwayFirewall:
    @pytest.mark.parametrize("field,value", [
        ("arm_value", 99.0),
        ("desired_target_modulation", "decrease"),
        ("target_id", "ENSG00000003436"),
        ("observed_perturbation_modality", "CRISPRi_knockdown"),
        ("phenocopy_class", "inhibition_observed_compatible"),
    ])
    def test_a_pathway_context_carrying_a_target_evidence_field(self, forged, field, value):
        """A gene set wearing a target's clothes, ready to be prescribed a drug."""
        W3F.reseal_bridge(forged["stage2_bridge"],
                          lambda d: d["pathway_contexts"][0].update({field: value}))
        _repoint(forged)
        _refuses(forged, sb.GATE_PATHWAY_CONTEXT_IS_TARGET_EVIDENCE)

    def test_the_forbidden_set_is_W3s_own(self):
        assert sb.CTX_FORBIDDEN == frozenset({
            "arm_value", "desired_target_modulation", "phenocopy_class", "evaluable", "rank",
            "target_id", "observed_perturbation_modality", "program_effect_direction",
            "supported", "phenocopy_claim"})


class TestTheDuplicateNativeIdentity:
    def test_two_native_records_under_one_identity_are_REFUSED(self, forged):
        from dataclasses import replace
        aggregate = _aggregate(forged)
        assert sb.native_index(aggregate), "non-vacuous: the native bytes carry rows"

        arm = next(a for a in aggregate.arms if a.lane in sa.MEASURED_LANES)
        doubled = replace(arm, records=arm.records + (dict(arm.records[0], arm_value=-1.0),))
        broken = replace(aggregate, arms=tuple(
            doubled if a.arm_key == arm.arm_key and a.lane == arm.lane else a
            for a in aggregate.arms))
        with pytest.raises(sa.Stage2BridgeError, match=sb.GATE_DUPLICATE_NATIVE_ROW):
            sb.native_index(broken)


class TestTheSignRuleIsREDERIVED:
    @pytest.mark.parametrize("value,evaluable,expected", [
        (0.5, True, "decrease"),          # the knockdown helped -> an inhibitor may phenocopy it
        (-0.5, True, "increase"),         # ...and this is NOT an agonist recommendation
        (0.0, True, "no_direction_evidence"),
        (1e-10, True, "no_direction_evidence"),      # inside SIGN_EPS
        (0.5, False, "not_evaluated"),
        (None, True, "not_evaluated"),
    ])
    def test_the_modulation_comes_from_the_native_value_alone(self, value, evaluable, expected):
        assert sb.rederive_modulation(value, evaluable=evaluable) == expected

    def test_the_eps_is_stage2s_own(self):
        assert sb.SIGN_EPS == 1e-9


def _repoint(paths) -> None:
    """Re-point the report and the receipt at the RESEALED bridge — the strongest attack.

    The forger owns the whole chain: the bridge re-seals, the report is made to name the new
    bytes, and the receipt binds them. Every hash agrees with every other hash. The ONLY thing
    left is whether the rows still agree with the bytes Stage 2 actually admitted.
    """
    import hashlib
    with open(paths["stage2_bridge"], "rb") as fh:
        raw = hashlib.sha256(fh.read()).hexdigest()
    doc = json.load(open(paths["stage2_bridge"]))
    canonical = sb.canonical_sha256(doc)
    W3F.rewrite(paths["stage2_bridge_report"],
                lambda d: d["judged_bridge"].update({"raw_sha256": raw,
                                                     "canonical_sha256": canonical}))
    with open(paths["stage2_bridge_report"], "rb") as fh:
        report_raw = hashlib.sha256(fh.read()).hexdigest()

    def fix(d):
        d["bridge"].update({"raw_sha256": raw, "canonical_sha256": canonical})
        d["bridge_report"].update({"raw_sha256": report_raw})
    W3F.reseal_receipt(paths["stage2_bridge_receipt"], fix)
