"""The REAL Stage-2 aggregate: 15 bundles, 300 reusable arm slots, and the native contract.

Every byte parsed here was GENERATED by Stage-2's own CLIs and admitted by its own separate
verifier (``stage2_release_fixture``). Nothing is hand-written, so the loader cannot drift
away from the producer without these tests going red.

Admission-chain refusals (identity, admission, bytes, paths) live in
``test_stage2_admission.py``.
"""
from __future__ import annotations

import dataclasses

import pytest
from druglink import stage2_aggregate as sa

from stage2_release_fixture import build_release

# The REAL admitted program axis, from the authoritative Stage-1 v3 release.
REAL_PROGRAMS = ("cd4_ctl_like", "diff_activated", "diff_checkpoint", "diff_memory",
                 "diff_naive", "tfh_like", "th17_like", "th1_like", "th2_like", "treg_like")


# --------------------------------------------------------------------------- #
# The native contract. NON-VACUOUS: nothing here can pass on an empty collection.
# --------------------------------------------------------------------------- #
def test_the_topology_is_exactly_15_bundles_and_300_arm_slots(admitted):
    assert len(admitted.bundles) == 15
    assert len(admitted.arms) == 300
    assert admitted.counts["bundles_per_lane"] == {"direct": 3, "temporal": 6, "pathway": 6}
    assert admitted.counts["arms_per_lane"] == {"direct": 60, "temporal": 120,
                                                "pathway": 120}
    assert len({b.bundle_key for b in admitted.bundles}) == 15
    assert len({b.bundle_id for b in admitted.bundles}) == 15     # DISTINCT invocations
    assert len({a.arm_key for a in admitted.arms}) == 300


def test_the_program_axis_is_the_releases_own_ten_programs(admitted):
    """Derived from the manifest's bound Stage-1 release, and checked against the arms."""
    assert admitted.program_ids == tuple(sorted(REAL_PROGRAMS))
    assert len(admitted.program_ids) == sa.N_PROGRAMS == 10


def test_the_counts_are_derived_from_the_conditions_not_copied(admitted):
    assert sa.N_BUNDLES == 3 + 6 + 6 == 15
    assert sa.N_ARM_SLOTS == 300
    assert len(sa.ordered_condition_pairs()) == 6
    assert ("Rest", "Stim48hr") in sa.ordered_condition_pairs()
    assert ("Stim48hr", "Rest") in sa.ordered_condition_pairs()    # a DISTINCT bundle
    assert admitted.counts["topology_is_derived_not_declared"] is True


def test_the_admission_is_stage2s_own_pinned_verifier(admitted):
    """The verifier id does NOT contain the word 'independent' — and never did.

    The retired gate required that substring, so it would have REFUSED this genuine report
    while admitting any forgery that simply named itself '…independent…'. Independence is the
    STRUCTURED FIELD ``generator_is_not_verifier``, which the loader binds.
    """
    assert admitted.verifier_id == sa.AGGREGATE_VERIFIER_ID
    assert admitted.verifier_id == "spot.stage02.run_manifest.verifier.v1"
    assert "independent" not in admitted.verifier_id
    assert admitted.verdict == sa.ADMIT == "admit"


def test_the_manifest_proves_its_own_semantic_identity(admitted, honest):
    """The self-hash is RE-DERIVED from the bytes, never read from the claim."""
    import json
    manifest = json.load(open(honest["manifest_path"]))
    report = json.load(open(honest["report_path"]))
    recomputed = sa.manifest_self_hash(manifest)

    assert len(recomputed) == 64
    assert admitted.manifest_self_hash == recomputed
    # the producer's claim, the verifier's recomputation and OURS are the same number
    assert manifest["manifest_sha256"] == recomputed
    assert report["manifest_sha256"] == report["manifest_sha256_recomputed"] == recomputed


def test_every_arm_retains_its_reusable_identity_and_context(admitted):
    assert admitted.arms, "non-vacuous guard: there must be arms to check"
    for arm in admitted.arms:
        assert arm.arm_key and arm.program_id in REAL_PROGRAMS
        assert arm.desired_change in sa.DESIRED_CHANGES
        assert arm.lane in sa.LANES
        ctx = arm.bundle                    # the arm's context, typed, never copied out
        if arm.lane == sa.LANE_TEMPORAL:
            assert ctx.from_condition and ctx.to_condition
            assert ctx.from_condition != ctx.to_condition       # an ORDERED pair
        elif arm.lane == sa.LANE_PATHWAY:
            assert ctx.condition and ctx.pathway_source in sa.PATHWAY_SOURCES
        else:
            assert ctx.condition in sa.CONDITIONS
        assert arm.ranking["raw_sha256"] and arm.ranking["canonical_sha256"]
        assert arm.provenance["manifest_self_hash"] == admitted.manifest_self_hash
        assert arm.provenance["aggregate_verifier_id"] == sa.AGGREGATE_VERIFIER_ID
        assert arm.records, "an arm with no records retains no target identity"


def test_an_arm_record_carries_STAGE2s_NATIVE_fields_and_nothing_invented(admitted):
    """Stage-2's reusable arm rankings carry exactly {target_id, arm_value, evaluable, rank}.

    The retired fixture gave every record a ``target_id_namespace``, ``target_symbol``,
    ``target_ensembl``, ``released_estimate_id`` and ``desired_target_modulation``. Stage 2
    emits NONE of those in a reusable arm bundle, so the loader carries what is there and
    invents nothing. A field Stage 2 does not emit is a field Stage 3 does not have.
    """
    native = {"target_id", "arm_value", "evaluable", "rank"}
    invented = {"target_id_namespace", "target_symbol", "target_ensembl",
                "released_estimate_id", "desired_target_modulation", "base_key"}
    seen: set = set()
    for arm in admitted.arms:
        for rec in arm.records:
            seen |= set(rec)
    assert seen, "non-vacuous guard: there must be records"
    assert seen == native, f"the native record shape drifted: {sorted(seen)}"
    assert not (seen & invented)


def test_an_unranked_target_arrives_as_NULL_never_zero_and_never_last(admitted):
    unranked = [r for a in admitted.arms for r in a.records if r["rank"] is None]
    assert unranked, "non-vacuous guard: the release must contain unranked (retained) rows"
    for rec in unranked:
        assert rec["rank"] is None and rec["rank"] != 0
    ranked = [r for a in admitted.arms for r in a.records if r["rank"] is not None]
    assert ranked and all(r["rank"] >= 1 for r in ranked)


def test_an_arm_carries_no_pair_role_no_pole_and_no_combined_score(admitted):
    names = {f.name for f in dataclasses.fields(sa.LoadedArm)}
    record_keys = set(admitted.arms[0].records[0])
    for banned in ("away_from_A", "toward_B", "role", "pole", "desired_arm",
                   "score", "combined_score", "total"):
        assert banned not in names and banned not in record_keys
    assert admitted.counts["pair_roles_assigned"] is False
    assert admitted.counts["combined_objective_permitted"] is False


# --------------------------------------------------------------------------- #
# The fixture firewall — STAGE-3's own class. Stage 2 declares none.
# --------------------------------------------------------------------------- #
def test_stage3s_own_artifact_class_is_what_the_firewall_reads(admitted, honest):
    """Stage 2 ships NO artifact_class; the class is Stage-3's declaration about its run.

    The retired fixture firewall keyed on ``manifest["artifact_class"]`` — a field that has
    never existed in a Stage-2 manifest, so it could only ever have read a fixture's own
    invention.
    """
    import json
    manifest = json.load(open(honest["manifest_path"]))
    assert "artifact_class" not in manifest        # the field the old loader keyed on
    assert admitted.artifact_class == "fixture"    # Stage-3's own --artifact-class


def test_a_fixture_run_is_refused_by_the_analysis_path(admitted):
    assert admitted.artifact_class == "fixture"    # non-vacuous
    with pytest.raises(sa.AggregateAdmissionRefused) as exc:
        sa.require_analysis(admitted)
    assert sa.GATE_FIXTURE_FIREWALL in str(exc.value)


def test_an_analysis_run_passes_the_firewall(honest):
    """The same REAL release, declared by Stage 3 as an analysis, walks the analysis path."""
    agg = sa.admit_aggregate(**honest, artifact_class="analysis")
    assert sa.require_analysis(agg) is agg
    assert len(agg.arms) == 300                   # non-vacuous


def test_an_unknown_artifact_class_is_refused(honest):
    from druglink import artifact_class as ac
    with pytest.raises(ac.ArtifactClassError):
        sa.admit_aggregate(**honest, artifact_class="production")


def test_the_stage1_release_is_bound_by_its_canonical_hash(admitted):
    assert len(admitted.stage1_release_sha256) == 64
    # exactly what the real manifest pins
    assert admitted.stage1_release_sha256.startswith("1624471068d74c99")


def test_a_second_build_of_the_same_release_is_byte_identical(tmp_path):
    """Determinism: the release is content-addressed, so two materialisations agree."""
    a = sa.admit_aggregate(**build_release(tmp_path / "a"))
    b = sa.admit_aggregate(**build_release(tmp_path / "b"))
    assert a.manifest_self_hash == b.manifest_self_hash
    assert len(a.arms) == len(b.arms) == 300
    assert {x.bundle_id for x in a.bundles} == {x.bundle_id for x in b.bundles}
