"""A Stage-2 release + BRIDGE generated by driving **W3's REAL producers and verifiers**.

NOTHING HERE IS HAND-AUTHORED. That is the whole point.

Stage 3 once invented an entire Stage-2 manifest schema and tested itself against its own
fiction — 34 green tests over a shape that did not exist, because one author wrote both the
loader and the fixture it parsed. So every artifact below is produced by the code that will
produce the real one, and then ADMITTED by that lane's own INDEPENDENT verifier:

  the 15 all-arm bundles      Stage-2's own ``fixtures_run_manifest`` builder
  target_identity.json        Stage-2's REAL ``direct.target_identity.build``
  stage2_run_manifest.json    Stage-2's REAL ``direct.run_manifest.build``
  the lane admissions         Stage-2's REAL ``direct.run_release.admitted_lanes``
  stage2_aggregate_…json      Stage-2's REAL ``direct.verify_run_manifest.verify``   -> ADMIT
  stage3_bridge.json          W3's REAL ``direct.stage3_bridge``  (the CLI, ``--verify``)
  stage3_bridge_verification  W3's REAL ``direct.verify_stage3_bridge``              -> ADMIT
  stage2_stage3_receipt.json  W3's REAL receipt emitter, independently re-verified   -> ADMIT

If a shape here were wrong, those verifiers would refuse it. That is the anti-fiction guarantee:
the fixture is validated by the PRODUCER'S OWN independent verifiers, not by Stage-3's say-so.

WHAT IS FIXTURE, AND WHAT IS REAL
---------------------------------
The arm VALUES are Stage-2 fixtures (synthetic — no science is asserted). The TARGET IDS are
REAL: they are drawn from the admitted universe store, so the join is a real join and the
emission is not vacuous. The schemas, the counts, the hashes, the chain and every ADMISSION are
real.

The bundles are W3's CURRENT native shape (``arms.parquet`` + ``target_identity.json`` on Direct,
an ``arm_key`` at the top of every ranking document, ``records`` on a pathway bundle). The
20260712 handoff predates all three, which is why the REAL gate stays closed until W3 emits a
release in this shape — this fixture proves the CONSUMER, not the release.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from typing import Any, Optional

import pytest

W3_ROOT = os.environ.get("SPOT_STAGE2_BRIDGE",
                         "/home/tcelab/worktrees/spot-stage2-runmanifest/02_geneskew")
UNIVERSE_STORE = os.environ.get(
    "SPOT_STAGE3_UNIVERSE_STORE",
    "/home/tcelab/.spot-runs/stage3-universe-20260713/store_w3tokens")

W3_ANALYSIS = os.path.join(W3_ROOT, "analysis")
W3_TESTS = os.path.join(W3_ROOT, "tests", "direct")

BRIDGE_FILE = "stage3_bridge.json"
BRIDGE_REPORT_FILE = "stage3_bridge_verification.json"
RECEIPT_FILE = "stage2_stage3_receipt.json"
MANIFEST_FILE = "stage2_run_manifest.json"
AGGREGATE_REPORT_FILE = "stage2_aggregate_verification.json"

SKIP_REASON = (
    f"W3's Stage-2 bridge producer is not on this host (looked in {W3_ROOT!r}; set "
    "SPOT_STAGE2_BRIDGE to override). Stage-3's bridge tests drive W3's ACTUAL producer and "
    "its ACTUAL independent verifier — they never hand-write a bridge document, because a "
    "hand-written fixture in an invented schema is the exact defect these tests exist to "
    "prevent.")


def _w3():
    """W3's producer + verifier + fixture builder, imported from THEIR worktree."""
    if not os.path.isfile(os.path.join(W3_ANALYSIS, "direct", "stage3_bridge.py")):
        pytest.skip(SKIP_REASON)
    if not os.path.isdir(UNIVERSE_STORE):
        pytest.skip(f"the admitted universe store is not on this host ({UNIVERSE_STORE!r})")
    for path in (W3_ANALYSIS, W3_TESTS):
        if path not in sys.path:
            sys.path.insert(0, path)
    try:
        import fixtures_run_manifest as F
        from direct import run_manifest, run_release, target_identity, verify_run_manifest
    except ImportError as exc:                      # pragma: no cover - host-dependent
        pytest.skip(f"{SKIP_REASON} (import failed: {exc})")
    return {"F": F, "run_manifest": run_manifest, "run_release": run_release,
            "target_identity": target_identity, "verify_run_manifest": verify_run_manifest}


class _Identity:
    """What ``target_identity.resolve`` hands the producer: a decided identity, per target."""

    def __init__(self, namespace: str, symbol: str, ensembl: Optional[str]) -> None:
        self.target_id_namespace = namespace
        self.target_symbol = symbol
        self.target_ensembl = ensembl


def real_identities(n_drugged: int = 8) -> dict[str, _Identity]:
    """REAL targets from the ADMITTED universe store — so the drug join is a real join.

    Drugged Ensembl accessions AND the four bare SYMBOL targets, because the universe is
    HETEROGENEOUS: a namespace guessed from an id's shape mistypes exactly those four, and three
    of them carry an ENSG-looking release key belonging to a DIFFERENT gene.
    """
    from druglink import universe_rows as ur
    store = ur.load_store(UNIVERSE_STORE)
    out: dict[str, _Identity] = {}
    for row in [r for r in store.rows if r["disposition"] == "drug_evidence"][:n_drugged]:
        tid = row["target_id"]
        out[tid] = _Identity("ensembl_gene_id", "SYM" + tid[-4:], tid)
    for row in store.rows:
        if row["target_id_namespace"] == "gene_symbol":
            # a SYMBOL target's Ensembl id is NULL, and it stays NULL
            out[row["target_id"]] = _Identity("gene_symbol", row["target_id"], None)
    return out


def _lane_of(ctx: dict) -> str:
    if "gene_set_source" in ctx:
        return "pathway"
    return "temporal" if "from_condition" in ctx else "direct"


def _patched_ranking(F, target_ids: list[str]):
    """Stage-2's OWN ranking fixture, over the REAL target ids, in W3's CURRENT shape.

    The one addition is ``arm_key`` at the top of the document — where W3's current temporal
    producer writes it, and where their bridge REQUIRES it ("Temporal stores it ONCE at the top
    level; its records do not repeat it"). The pathway lane is delegated UNTOUCHED: its
    ``n_hits_by_set`` is recomputed by Stage-2's aggregate verifier from the bound gene-set
    membership, and moving its targets would break a count nobody asked us to move.
    """
    original = F._ranking

    def ranking(program: str, dc: str, ctx: dict) -> dict[str, Any]:
        doc = original(program, dc, ctx)
        lane = _lane_of(ctx)
        if lane == "pathway":
            return doc
        sign = 1.0 if dc == "increase" else -1.0
        # base_delta(A->B) = -base_delta(B->A): the reverse of an ordered pair is the exact
        # negation, and Stage-2's cross-bundle gate says so.
        orient = (1.0 if lane == "direct"
                  else 1.0 if str(ctx["from_condition"]) < str(ctx["to_condition"]) else -1.0)
        records = [{"target_id": t, "arm_value": sign * orient * (len(target_ids) - i),
                    "evaluable": True, "rank": None}
                   for i, t in enumerate(target_ids)]
        for i, rec in enumerate(sorted(records,
                                       key=lambda r: (-r["arm_value"], r["target_id"]))):
            rec["rank"] = i + 1
        doc["records"] = records
        doc["n_ranked"] = doc["n_targets"] = len(records)
        doc["arm_key"] = "|".join(
            [lane, program, dc]
            + ([ctx["condition"]] if lane == "direct"
               else [ctx["from_condition"], ctx["to_condition"]]))
        return doc

    return ranking


def _direct_native_bytes(W, run, identities, target_ids) -> None:
    """The two native artifacts W3's bridge reads off a Direct bundle, by their REAL producer."""
    import pandas as pd

    for bundle_dir in run["direct"]:
        bundle = json.load(open(os.path.join(bundle_dir, "arm_bundle.json")))
        rows = []
        for arm in bundle["arms"]:
            doc = json.load(open(os.path.join(bundle_dir, arm["ranking"]["path"])))
            rows += [{"arm_key": arm["arm_key"], "program_id": arm["program_id"],
                      "desired_change": arm["desired_change"],
                      "condition": bundle["condition"], "target_id": r["target_id"],
                      "value": r["arm_value"], "rank": r["rank"],
                      "evaluable": r["evaluable"]}
                     for r in doc["records"]]
        pd.DataFrame(rows).to_parquet(os.path.join(bundle_dir, "arms.parquet"))
        # THE PRODUCER'S OWN artifact, built by the producer's own code.
        identity = W["target_identity"].build(
            identities, condition=bundle["condition"], scored_targets=set(target_ids))
        with open(os.path.join(bundle_dir, W["target_identity"].TARGET_IDENTITY_FILE), "w") as fh:
            json.dump(identity, fh, indent=2, sort_keys=True)


def _pathway_native_records(F, run, target_ids) -> None:
    """The pathway lane's native (arm x GENE SET) records — the grain W3's bridge reads.

    The bundle, its provenance and its preflight are re-sealed together, in the producer's own
    order, so the bundle still proves its own identity.
    """
    for bundle_dir in run["pathway"]:
        path = os.path.join(bundle_dir, "arm_bundle.json")
        inv = json.load(open(path))
        inv["records"] = [
            {"pathway_arm_key": arm["pathway_arm_key"], "set_id": set_id,
             "enrichment_value": 0.25, "target_source_coverage": 0.5,
             "convergence_ref": arm["convergence_id"], "source": inv["source"],
             "leading_edge": list(target_ids)}
            for arm in inv["arms"] for set_id in sorted(F.FIXTURE_SETS)]
        inv["n_records"] = len(inv["records"])
        inv.pop("pathway_run_id", None)
        native_id = "FIXTURE-" + F._canon(inv)[:16]
        inv["pathway_run_id"] = native_id
        arm_raw, _ = F._write(path, inv)

        prov_path = os.path.join(bundle_dir, "pathway_provenance.json")
        prov = json.load(open(prov_path))
        prov["bundle_id"] = F._norm(inv)["bundle_id"]
        prov_raw, _ = F._write(prov_path, prov)

        ver_path = os.path.join(bundle_dir, "pathway_verification.json")
        ver = json.load(open(ver_path))
        ver["bundle_id"] = native_id
        ver["binds"] = {"arm_bundle_sha256": arm_raw, "provenance_sha256": prov_raw}
        F._write(ver_path, ver)


def build_release(root: str, *, n_drugged: int = 8) -> dict[str, Any]:
    """The ADMITTED Stage-2 release + W3's ADMITTED bridge, receipt and reports.

    Returns every path Stage-3's ``--v2`` CLI consumes. Raises if any of Stage-2's or W3's own
    independent verifiers refuses — a fixture nobody admitted is not a fixture, it is a claim.
    """
    W = _w3()
    F = W["F"]
    identities = real_identities(n_drugged)
    target_ids = sorted(identities)

    original = F._ranking
    try:
        F._ranking = _patched_ranking(F, target_ids)
        run = F.complete_run(root)
    finally:
        F._ranking = original

    bundles_root = run["root"]
    _direct_native_bytes(W, run, identities, target_ids)
    _pathway_native_records(F, run, target_ids)
    F.seal_release(run)             # re-derive every lane inventory + admission from the bytes

    # --- Stage-2's REAL aggregate manifest, over the lanes it REALLY admitted ---------- #
    admitted, refused = W["run_release"].admitted_lanes(bundles_root)
    if refused:
        raise AssertionError(f"Stage-2 refused its own lanes: {refused[:3]}")
    manifest_path = os.path.join(bundles_root, MANIFEST_FILE)
    W["run_manifest"].build(
        bundles=[W["run_manifest"].bind_bundle(d)
                 for d in run["direct"] + run["temporal"] + run["pathway"]],
        out_path=manifest_path,
        release=W["run_manifest"].load_release(run["release_path"], run["release_root"]),
        lane_admissions=admitted,
        code_identity={"commit": "f" * 40, "clean_tree": True,
                       "manifest_sha256": "0" * 64, "canonical_digest": "0" * 16})

    # --- ...and Stage-2's REAL INDEPENDENT aggregate verifier. ADMIT, or no fixture. ---- #
    report = W["verify_run_manifest"].verify(
        manifest_path=manifest_path, bundles_root=bundles_root,
        release_path=run["release_path"], release_root=run["release_root"],
        expect_release_sha256=run["expect_release_sha256"],
        expect_gene_sets_path=run["pinned_gene_sets"],
        expect_verifiers_path=run["pinned_verifiers"],
        expected_code_identity_path=run["expected_code_identity"],
        env_lock_path=run["env_lock"], expect_env_lock_sha256=F.env_lock_sha256(run))
    if report["verdict"] != "admit" or report.get("n_failed"):
        raise AssertionError(f"Stage-2's aggregate verifier REFUSED the fixture release: "
                             f"{report.get('failed_gates')}")
    report_path = os.path.join(bundles_root, AGGREGATE_REPORT_FILE)
    with open(report_path, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, sort_keys=True)

    # --- W3's REAL bridge CLI: build, INDEPENDENTLY verify, and write the RECEIPT ------- #
    proc = subprocess.run(
        [sys.executable, "-m", "direct.stage3_bridge", "--bundles-root", bundles_root,
         "--bridge-root", bundles_root, "--verify"],
        env=dict(os.environ, PYTHONPATH=W3_ANALYSIS), cwd=W3_ROOT,
        capture_output=True, text=True)
    if proc.returncode != 0:
        raise AssertionError(f"W3's bridge CLI refused the fixture release (exit "
                             f"{proc.returncode}):\n{proc.stdout[-2000:]}\n{proc.stderr[-800:]}")

    return {
        "bundles_root": bundles_root,
        "stage2_manifest": manifest_path,
        "stage2_report": report_path,
        "stage1_release": run["release_path"],
        "stage2_bridge": os.path.join(bundles_root, BRIDGE_FILE),
        "stage2_bridge_report": os.path.join(bundles_root, BRIDGE_REPORT_FILE),
        "stage2_bridge_receipt": os.path.join(bundles_root, RECEIPT_FILE),
        "universe_store": UNIVERSE_STORE,
        "target_ids": target_ids,
        "run": run,
    }


# --- Re-sealing, for the mutation attacks. -------------------------------------- #
def reseal_bridge(path: str, mutate) -> dict[str, Any]:
    """Edit the bridge and RE-SEAL its self-hash — what a forger with repo access does.

    An attack that could not re-seal would be no attack at all: the gates must stop a CONSISTENT
    forgery, not a careless one.
    """
    from druglink.stage2_bridge import self_hash
    doc = json.load(open(path))
    mutate(doc)
    doc["bridge_sha256"] = self_hash(doc, "bridge_sha256")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, sort_keys=True)
    return doc


def reseal_receipt(path: str, mutate) -> dict[str, Any]:
    from druglink.stage2_bridge import self_hash
    doc = json.load(open(path))
    mutate(doc)
    doc["receipt_sha256"] = self_hash(doc, "receipt_sha256")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, sort_keys=True)
    return doc


def rewrite(path: str, mutate) -> dict[str, Any]:
    """Edit a document WITHOUT re-sealing (a report has no self-hash to re-seal)."""
    doc = json.load(open(path))
    mutate(doc)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, sort_keys=True)
    return doc
